import type { Event, EventCategory } from "./types";
import type { Locale } from "@/i18n/config";
import { FALLBACK_EVENTS_FR } from "./fallback-events-fr";
import { getRecurringEvents } from "./recurring-events";
import { materializeEventDates } from "./event-dates";
import { filterRemovedSeedEvents } from "./removed-seeds";
import { eventInCategory, withResolvedCategories } from "./categorize";
import {
  ATLETICOS_HOME_GAMES_EN,
  ATLETICOS_HOME_GAMES_ES,
} from "./atleticos-summer-league-2026";
import {
  ASA_SURVIVAL_SERIES_EN,
  ASA_SURVIVAL_SERIES_ES,
} from "./asa-survival-series-2026";
import {
  EL_CAREY_WC2026_EVENTS_EN,
  EL_CAREY_WC2026_EVENTS_ES,
  EL_CAREY_WC2026_EVENTS_FR,
} from "./world-cup-2026-events";

const FALLBACK_EVENTS_EN: Event[] = [
  // Music
  {
    id: "voyvoy-sunday-open-mic",
    title: "VOYVOY Sunday Open Mic & Jam",
    description:
      "Live music, open mic, and jam night at VOYVOY in Cabarete. Lester Grant kicks it off — bring an instrument or borrow one. Relaxed drinks and dinner spot.",
    date: "2026-07-05",
    time: "5:00 PM – 11:00 PM",
    location: "Cabarete",
    venue: "VOYVOY Cabarete",
    venueSlug: "voyvoy-cabarete",
    category: "performances",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 0,
    imageEmoji: "🎤",
  },
  {
    id: "voyvoy-saturday-session",
    title: "VOYVOY Saturday Session",
    description:
      "Saturday night dance session at VOYVOY with guest DJs — reggaeton, dance club vibes, no cover. A Cabarete staple for locals and visitors.",
    date: "2026-07-11",
    time: "9:00 PM – 2:00 AM",
    location: "Cabarete",
    venue: "VOYVOY Cabarete",
    venueSlug: "voyvoy-cabarete",
    category: "parties",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6,
    imageEmoji: "🪩",
  },
  {
    id: "la-chabola-wednesday-open-mic",
    title: "La Chabola Wednesday Open Mic",
    description:
      "Wednesday open mic at La Chabola in Callejón de la Loma, Cabarete — local musicians, stone-oven pizza, and a neighborhood crowd. Bring a song or just listen; doors from late afternoon, music into the night.",
    date: "2026-07-22",
    time: "8:00 PM – 12:00 AM",
    location: "Cabarete",
    venue: "La Chabola",
    venueSlug: "la-chabola-cabarete",
    address: "Callejón de la Loma, Cabarete 57000",
    lat: 19.7475887,
    lng: -70.4167516,
    category: "performances",
    categories: ["music"],
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 3,
    phone: "+18095435860",
    sourceUrl: "https://www.facebook.com/chabolacabaretee",
    imageEmoji: "🎤",
  },
  {
    id: "groundzero-domingos-pal-pueblo",
    title: "Domingos Pal Pueblo at Ground Zero",
    description:
      "Sunday party nights at Ground Zero Discoteca — reggaeton, dembow, baile típico, and urban hits with DJs all night, whisky half-price, and hookah. On the Puerto Plata–Sosúa highway opposite the airport. Reserve a table: 849-465-1313.",
    date: "2026-07-19",
    time: "9:00 PM – 4:00 AM",
    location: "Sosúa",
    venue: "Ground Zero Discoteca",
    venueSlug: "ground-zero-disco",
    address:
      "Km 18, Carretera Puerto Plata–Sosúa, frente al Aeropuerto Gregorio Luperón",
    lat: 19.76,
    lng: -70.565,
    category: "parties",
    categories: ["music", "dance"],
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 0,
    phone: "+18494651313",
    callForPricing: true,
    trending: true,
    sourceUrl: "https://www.instagram.com/groundzero_disco/p/DayWu9phE9R/",
    imageEmoji: "🪩",
  },
  {
    id: "lil-naay-2026-07-17",
    title: "Lil Naay — Live at Disco Club",
    description:
      "Dominican urban star Lil Naay live at Disco Club (Depósitos de Brugal, Calle Duarte) — Friday Jul 17, 8–11 PM. Pre-sale RD$700 on todotickets.do (service included); electronic QR entry at the door.",
    date: "2026-07-17",
    time: "8:00 PM – 11:00 PM",
    location: "Puerto Plata",
    address: "Depósitos de Brugal, Calle Duarte",
    venue: "Disco Club",
    venueSlug: "disco-club-brugal",
    lat: 19.7966,
    lng: -70.6923,
    category: "concert",
    format: "physical",
    trending: true,
    isFree: false,
    admissionPrice: "RD$700",
    sourceUrl: "https://todotickets.do/events/lil-naay",
    ticketUrl: "https://todotickets.do/events/lil-naay",
    lineup: ["Lil Naay"],
    imageEmoji: "🎤",
  },
  {
    id: "lena-dardelet-aura-beach-club-2026-07-24",
    title: "Lena Dardelet × Pororó — De Aquí Pa'llá",
    description:
      "French-Dominican singer-songwriter Lena Dardelet and Pororó open their national De Aquí Pa'llá tour at Aura Beach Club on Cabarete's Calle Principal — Friday Jul 24, 8 PM AST. Free entry with RSVP on tix.do.",
    date: "2026-07-24",
    time: "8:00 PM",
    location: "Cabarete",
    venue: "Aura Beach Club Cabarete",
    venueSlug: "aura-beach-club-cabarete",
    address: "Calle Principal 5, Cabarete 57000",
    lat: 19.7500769,
    lng: -70.4070417,
    category: "concert",
    categories: ["music"],
    format: "physical",
    trending: true,
    isFree: true,
    phone: "+18297870140",
    sourceUrl:
      "https://www.bandsintown.com/e/108603887-lena-dardelet-at-aura-beach-club-cabarete",
    ticketUrl:
      "https://tix.do/event/PororoyLenaDardeletdeaquipallaencabarete-1",
    lineup: ["Lena Dardelet", "Pororó"],
    imageEmoji: "🎤",
  },
  {
    id: "cabarete-jazz-festival-2026",
    title: "Cabarete Jazz Festival 2026",
    description:
      "Second edition of Cabarete Jazz Festival (Sat Jun 6) — Alfredo Rodríguez, Cimafunk, Los Amigos Invisibles, iLe, Gia Fu, and Dominican saxophonist Sandy Gabriel. Open-air Caribbean jazz produced by Cabarete Tango and Mishu Music; gates from 5 PM. Tickets at cabaretejazz.com.",
    date: "2026-06-06",
    time: "5:00 PM – 11:00 PM",
    location: "Cabarete",
    venue: "Cabarete Jazz Festival Grounds",
    lat: 19.770325,
    lng: -70.43824,
    category: "festivals",
    categories: ["concert", "music"],
    format: "physical",
    trending: true,
    sourceUrl: "https://www.cabaretejazz.com/",
    ticketUrl: "https://www.cabaretejazz.com/",
    lineup: [
      "Alfredo Rodríguez",
      "Cimafunk",
      "Los Amigos Invisibles",
      "iLe",
      "Gia Fu",
      "Sandy Gabriel",
    ],
    imageEmoji: "🎷",
  },
  {
    id: "jandy-ventura-legado-caballo-2026",
    title: "Jandy Ventura — El Legado del Caballo",
    description:
      "Jandy Ventura brings the Johnny Ventura merengue tribute “El Legado del Caballo” to the Blue JackTar convention center in Playa Dorada. Tickets sold locally at Supermercado José Luis, Tío Pan, Blue JackTar, and La Locanda — Front Stage RD$5,000 · VIP RD$4,000 · General RD$2,500. Produced by GRAAN Events Planners.",
    date: "2026-07-30",
    time: "8:00 PM",
    location: "Puerto Plata",
    venue: "Blue JackTar Playa Dorada",
    venueSlug: "blue-jacktar-playa-dorada",
    address: "Centro de Convenciones, Playa Dorada",
    lat: 19.7703,
    lng: -70.6494,
    category: "concert",
    categories: ["music"],
    format: "physical",
    trending: true,
    admissionPrice: "RD$2,500–5,000",
    phone: "+18098898853",
    sourceUrl:
      "https://puertoplatadigital.com/puerto-plata-de-noche/el-legado-del-caballo-llega-a-puerto-plata",
    lineup: ["Jandy Ventura"],
    imageEmoji: "🎶",
  },
  // Sports
  {
    id: "rumble-in-paradise-12",
    title: "Rumble in Paradise 12",
    description:
      "Professional boxing on Sosúa Beach at Bar 39, with special guest appearances and autograph signings.",
    date: "2026-07-04",
    time: "5:00 PM – 9:00 PM",
    location: "Sosúa",
    venue: "Bar 39, Sosúa Beach",
    venueSlug: "bar-39-sosua",
    category: "sports",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/events/1614506996278636",
    imageEmoji: "🥊",
  },
  ...ATLETICOS_HOME_GAMES_EN,
  ...ASA_SURVIVAL_SERIES_EN,
  {
    id: "cabarete-classic-2026",
    title: "Cabarete Classic 2026",
    description:
      "Four days of windsurf, kitesurf, wingfoil, and foil racing on Cabarete Beach (Jul 16–19). The Caribbean's flagship water-sports regatta — international competitors, clinics, and evening music on the beach.",
    date: "2026-07-16",
    endDate: "2026-07-19",
    time: "9:00 AM – 11:00 PM",
    location: "Cabarete",
    venue: "Cabarete Beach",
    venueSlug: "kite-beach",
    address: "Residencial Mañanero, Cabarete",
    category: "sports",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/events/4550504901861035/",
    imageEmoji: "🏄",
  },
  {
    id: "puerto-plata-golf-classic-2026",
    title: "Puerto Plata Golf Classic 2026",
    description:
      "13th edition of Ashonorte's Puerto Plata Golf Classic — scramble pairs tournament at Playa Dorada Golf Course on Saturday Jul 18, with a Night Putting Challenge and categories named for North Coast towns (Puerto Plata, Sosúa, Cabarete, La Isabela). Registration US$210 via the golf club; call +1 809 320 4262.",
    date: "2026-07-18",
    time: "7:00 AM – 9:00 PM",
    location: "Playa Dorada",
    venue: "Playa Dorada Golf Course",
    venueSlug: "playa-dorada-golf",
    address: "Playa Dorada, Puerto Plata",
    lat: 19.7635,
    lng: -70.6555,
    category: "sports",
    format: "physical",
    trending: true,
    admissionPrice: "US$210",
    phone: "+18093204262",
    sourceUrl: "https://playadoradagolf.com/en/event/puerto-plata-golf-classic/",
    imageEmoji: "⛳",
  },
  {
    id: "cac-games-surf-playa-encuentro-2026",
    title: "CAC Games Surf — Playa Encuentro",
    description:
      "Surf competitions for the XXV Central American and Caribbean Games Santo Domingo 2026 at Playa Encuentro, Cabarete (Jul 25–29). Shortboard, longboard, and SUP Surf for men and women — 71 athletes from 12 countries on the North Coast's signature break. Most CAC competitions are free for spectators; organizers: +1 829 893 4214.",
    date: "2026-07-25",
    endDate: "2026-07-29",
    time: "8:00 AM – 6:00 PM",
    location: "Cabarete",
    venue: "Playa Encuentro",
    venueSlug: "playa-encuentro",
    address: "Playa Encuentro, Cabarete",
    lat: 19.7808,
    lng: -70.4825,
    category: "sports",
    format: "physical",
    trending: true,
    isFree: true,
    phone: "+18298934214",
    sourceUrl:
      "https://diamantedominicano.com/2026/05/playa-encuentro-en-cabarete-sera-sede-oficial-del-surf-en-los-juegos-centroamericanos-y-del-caribe-2026/",
    imageEmoji: "🏄",
  },
  {
    id: "puerto-plata-beach-soccer-2026",
    title: "Puerto Plata Beach Soccer 2026",
    description:
      "Second edition of Puerto Plata Beach Soccer at Playa Los Charamicos, Sosúa (Aug 21–23). Six senior teams and six U-15 sides compete over three family-friendly days promoting beach soccer and North Coast sports tourism. Free beach spectating; team/info inquiries +1 809 586 6125.",
    date: "2026-08-21",
    endDate: "2026-08-23",
    time: "9:00 AM – 6:00 PM",
    location: "Sosúa",
    venue: "Playa Los Charamicos",
    venueSlug: "playa-los-charamicos",
    address: "Playa Los Charamicos, Sosúa",
    lat: 19.7542,
    lng: -70.5285,
    category: "sports",
    format: "physical",
    trending: true,
    isFree: true,
    phone: "+18095866125",
    sourceUrl:
      "https://puertoplatadigital.com/deportes/puerto-plata-beach-soccer-regresa-con-su-segunda-edicion-del-21-al-23-de-agosto-en-sosua",
    imageEmoji: "⚽",
  },
  {
    id: "sosua-10k-road-race-2026",
    title: "11th Sosúa 10K Road Race",
    description:
      "11th annual Sosúa 10K organized by the Sosúa Sustainable Development Association (ADSS) — a 10K through downtown El Batey plus a children's 1K (under 12). Starts Sunday Oct 11 at 6:45 AM at Parque Las Flores; register by Oct 7 midnight on sdctickets.do from RD$500. Spectators welcome. Info: +1 809 571 2100 · WhatsApp +1 829 546 7528.",
    date: "2026-10-11",
    time: "6:45 AM",
    location: "Sosúa",
    venue: "Parque Las Flores, El Batey",
    venueSlug: "el-batey-sosua",
    address: "Parque Las Flores, El Batey, Sosúa",
    lat: 19.7675,
    lng: -70.5115,
    category: "sports",
    format: "physical",
    trending: true,
    admissionPrice: "RD$500",
    phone: "+18095712100",
    sourceUrl: "https://sea-horse-ranch.com/sosua-10k-road-race/",
    ticketUrl: "https://www.sdctickets.do/detail/479",
    imageEmoji: "🏃",
  },
  {
    id: "puerto-plata-poker-experience-2026",
    title: "Puerto Plata Poker Experience (CLSOP)",
    description:
      "Ten-day Caribbean poker festival at Coral Reef Casino in Sosúa Bay Center (Aug 28–Sep 6) — 15 tournaments in US dollars, cash games, and an NLH Main Event with a US$100,000 guarantee (US$900 buy-in, unlimited re-entries). Oceanfront series on the CLSOP circuit.",
    date: "2026-08-28",
    endDate: "2026-09-06",
    time: "See schedule",
    location: "Sosúa",
    venue: "Coral Reef Casino",
    address: "Dr. Alejo Martínez #1, Edif. Sosúa Bay Center, El Batey, Sosúa",
    lat: 19.7566,
    lng: -70.513,
    category: "festivals",
    format: "physical",
    trending: true,
    admissionPrice: "Main Event US$900 buy-in",
    sourceUrl: "https://www.clsop.com/",
    ticketUrl: "https://www.clsop.com/",
    imageEmoji: "🃏",
  },
  {
    id: "aventurate-rd-2026",
    title: "Aventúrate RD 2026",
    description:
      "Second edition of Aventúrate RD, the North Coast's adventure- and eco-tourism business fair, at Hotel Marién in Puerto Plata (Sep 2–4). 60+ exhibitors and 200+ international buyers, plus forums, business rounds, and a gastronomic closing in Sosúa. Organized by AFEET RD and CDCT; register at feriaaventuraterd.com.",
    date: "2026-09-02",
    endDate: "2026-09-04",
    time: "9:00 AM – 8:00 PM",
    location: "Puerto Plata",
    venue: "Hotel Marién",
    address: "Costa Dorada, Puerto Plata",
    lat: 19.8206,
    lng: -70.7079,
    category: "festivals",
    categories: ["culture"],
    format: "physical",
    trending: true,
    sourceUrl: "https://feriaaventuraterd.com/",
    ticketUrl: "https://feriaaventuraterd.com/",
    imageEmoji: "🌿",
  },
  {
    id: "sunset-cabarete-sessions-2026",
    title: "Sunset Cabarete Sessions",
    description:
      "Two-day beachfront deep-house sessions at Lux Beach Bar on Playa Cabarete (Dec 5–6) — kite surf by day, sunset transitions, resident DJs, and German guest Acid Pauli. Barefoot, 18+, local craft beer; 2 PM–1 AM. Tickets from US$16 on Ticketplus.",
    date: "2026-12-05",
    endDate: "2026-12-06",
    time: "2:00 PM – 1:00 AM",
    location: "Cabarete",
    venue: "Lux Beach Bar",
    address: "Playa Cabarete, Cabarete",
    lat: 19.7515,
    lng: -70.4098,
    category: "parties",
    categories: ["music"],
    format: "physical",
    trending: true,
    isFree: false,
    admissionPrice: "from US$16",
    sourceUrl: "https://dominicana.myticketplus.com/events/sunset-cabarete-sessions",
    ticketUrl: "https://dominicana.myticketplus.com/events/sunset-cabarete-sessions",
    lineup: ["Acid Pauli"],
    imageEmoji: "🎧",
  },
  {
    id: "womens-reconnection-kite-camp-2026",
    title: "Women's Reconnection Kite Camp",
    description:
      "7-night women's kite camp on Cabarete beachfront — flow, reconnect, and kite sessions with IKO instructor Ariadna Rabasa. Early bird spots available.",
    date: "2026-08-01",
    endDate: "2026-08-08",
    time: "8:00 AM – 8:00 PM",
    location: "Cabarete",
    venue: "Cabarete Beach",
    venueSlug: "kite-beach",
    category: "sports",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/events/1683911749456298/",
    imageEmoji: "🏄",
  },
  {
    id: "ingest-18th-annual-cabarete-butterfly-effect",
    title: "18th Annual Cabarete Butterfly Effect",
    description:
      "Five-day women's watersports festival across Cabarete (Jul 7–11): SUP clinics, yoga, beach cleanup, catamaran cruise, and the signature river paddle. See the official site for schedule and registration.",
    date: "2026-07-07",
    endDate: "2026-07-11",
    time: "9:00 AM – 9:00 PM",
    location: "Cabarete",
    venue: "Kite Beach & Cabarete town",
    address: "Carretera 5",
    venueSlug: "kite-beach",
    category: "festivals",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.cabaretebutterflyeffect.com/",
    imageEmoji: "🏄",
  },
  // Food & Drinks
  {
    id: "sancocho-sabados-pingui",
    title: "Sancocho Saturdays at Pingüi",
    description:
      "Saturdays taste like tradition at Pingüi Bar — share a bowl of sancocho facing the sea at Playa El Pueblito. Gather friends and family for an afternoon of Dominican comfort food and ocean views (12–4 PM).",
    date: "2026-07-11",
    time: "12:00 PM – 4:00 PM",
    location: "Puerto Plata",
    venue: "Pingüi Bar Restaurant & Piña Colada House",
    venueSlug: "pingui-bar",
    address: "C. B, Puerto Plata 57000",
    lat: 19.773903,
    lng: -70.652704,
    category: "food-drinks",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6,
    sourceUrl:
      "https://www.facebook.com/events/1547520700301499/1547522116968024/",
    imageEmoji: "🍲",
  },
  // Festivals
  {
    id: "feria-artesanal-verano-2026",
    title: "Feria Artesanal Verano 2026",
    description:
      "The Summer Artisan Fair 2026 runs July 10–26 at Plaza Independencia (Puerto Plata's Central Park). More than 120 local artisans exhibit daily from 8:00 AM to 9:00 PM — handmade pieces, cultural displays, art, souvenirs, and cabezudos masks. A showcase of Dominican crafts for visitors and residents alike.",
    date: "2026-07-10",
    endDate: "2026-07-26",
    time: "8:00 AM – 9:00 PM",
    location: "Puerto Plata",
    venue: "Plaza Independencia (Parque Central)",
    venueSlug: "plaza-independencia",
    address: "Calle San Felipe, Puerto Plata",
    category: "festivals",
    categories: ["culture"],
    format: "physical",
    trending: true,
    isFree: true,
    sourceUrl: "https://www.facebook.com/share/18vHNaoe69/",
    imageEmoji: "🎨",
  },
  {
    id: "puerto-plata-carnaval-2026",
    title: "Puerto Plata Carnival 2026",
    description:
      "Puerto Plata Carnival 2026 on the Malecón — Sunday parades every February (Feb 1, 8, 15 & 22) culminating in the Gran Desfile Final on March 1 at Anfiteatro La Puntilla. Taimáscaro masks, comparsas, and Dominican folk culture on the North Coast.",
    date: "2026-02-01",
    endDate: "2026-03-01",
    time: "2:00 PM – 8:00 PM",
    location: "Puerto Plata",
    venue: "Malecón de Puerto Plata & Anfiteatro La Puntilla",
    venueSlug: "malecon-puerto-plata",
    category: "festivals",
    format: "physical",
    trending: true,
    sourceUrl:
      "https://sea-horse-ranch.com/carnival-celebrations-in-the-dominican-republic/",
    imageEmoji: "🎭",
  },
  // Dance
  // Health & Wellness
  {
    id: "malecon-morning-wellness-walk",
    title: "Malecón Morning Wellness Walk",
    description:
      "Early-morning walkers and joggers along Puerto Plata's Malecón — ocean breezes, stretching groups, and a daily wellness ritual on the waterfront promenade from La Puntilla to the city center.",
    date: "2026-01-01",
    time: "6:00 AM – 8:00 AM",
    location: "Puerto Plata",
    venue: "Malecón de Puerto Plata",
    venueSlug: "malecon-puerto-plata",
    category: "health-wellness",
    format: "physical",
    recurrence: "daily",
    imageEmoji: "🚶",
  },
  {
    id: "cabarete-pilates-reformer",
    title: "Pilates Reformer Group Class",
    description:
      "Group Pilates Reformer sessions in Cabarete with Rafaella Cirillo (Tue & Thu 9 AM). Studio address shared when you book — DM or WhatsApp +1 809 460 5777. Discount code RC-pilates for first class.",
    date: "2026-07-08",
    time: "9:00 AM – 10:00 AM",
    location: "Cabarete",
    venue: "Rafaella's Studio",
    category: "health-wellness",
    format: "physical",
    recurrence: "weekly",
    recurrenceDays: [2, 4],
    sourceUrl: "https://www.facebook.com/events/981611704653706/",
    imageEmoji: "🧘",
  },
  // Performances
  {
    id: "el-colibri-karaoke-battle-2026",
    title: "El Colibri Karaoke Battle — Thursdays",
    description:
      "Thursday karaoke nights at El Colibri Hotel, Sosúa (7 PM–midnight). Join the 8-week Karaoke Battle — $20,000 in prizes (Jul 2–Sep 3, 2026). Contestants must attend every Thursday to stay eligible. Register on WhatsApp: +1 917-523-7259.",
    date: "2026-07-02",
    endDate: "2026-09-03",
    time: "7:00 PM – 12:00 AM",
    location: "Sosúa",
    venue: "El Colibri Hotel",
    venueSlug: "el-colibri-hotel",
    address: "141 Pedro Clisante, Sosúa 57600",
    lat: 19.7545,
    lng: -70.519,
    category: "music",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 4,
    trending: true,
    sourceUrl: "https://www.elcolibriresort.com/",
    imageEmoji: "🎤",
  },
  // Business
  // Parties
  {
    id: "inicio-del-campamento-pp-2026",
    title: "Inicio del Campamento",
    description:
      "Sports camp kickoff in historic San Felipe, Puerto Plata — hosted by Sin pelos en la lengua. Check the Facebook event for registration details.",
    date: "2026-07-10",
    time: "5:00 PM – 8:00 PM",
    location: "Puerto Plata",
    venue: "San Felipe de Puerto Plata",
    venueSlug: "fortaleza-san-felipe",
    category: "sports",
    format: "physical",
    sourceUrl: "https://www.facebook.com/events/1017381540870816/",
    imageEmoji: "⚽",
  },
  {
    id: "silent-run-5k-2026-07-25",
    title: "Silent Run 5K — Malecón Puerto Plata",
    description:
      "Immersive 5K along the Puerto Plata Malecón with wireless headphones synced to a live DJ — hosted by Aleva Experiences. Meet at Victrola 037 Arte Café; neon after-party, raffles, and prizes after the route. Tickets from RD$950 on boletu.com (phases sold out — join the waitlist).",
    date: "2026-07-25",
    time: "6:00 AM",
    location: "Puerto Plata",
    venue: "Victrola 037 Arte Café",
    venueSlug: "victrola-037",
    address: "Av. Gral. Gregorio Luperón esq. Padre Castellanos, Puerto Plata 57000",
    lat: 19.7975,
    lng: -70.6928,
    category: "sports",
    categories: ["health-wellness"],
    format: "physical",
    trending: true,
    isFree: false,
    admissionPrice: "RD$950–1,100",
    sourceUrl: "https://www.facebook.com/events/1290779933223443",
    ticketUrl: "https://boletu.com/event/silent-run-5k",
    imageEmoji: "🎧",
  },
  {
    id: "piscinazo-pop-urbano-037-2026-08-02",
    title: "Piscinazo POP Urbano 037 — 1st Edition",
    description:
      "First 2026 pool-party showcase from Pop Urbano 037 under the Black & White Music and Entertainment label — five Puerto Plata singers take the stage. Venue TBA in San Felipe; follow the Facebook event for lineup votes and details.",
    date: "2026-08-02",
    time: "10:00 AM",
    location: "Puerto Plata",
    venue: "San Felipe de Puerto Plata",
    category: "parties",
    categories: ["music"],
    format: "physical",
    trending: true,
    callForPricing: true,
    sourceUrl: "https://www.facebook.com/events/979095458299610",
    imageEmoji: "🏊",
  },
  {
    id: "los-event-trilogy-2026-09-03",
    title: "LOS Event — Trilogy Labor Day Weekend",
    description:
      "Multi-day Labor Day 2026 party takeover by Trilogy World at VIP Beach Lifestyles Resort and Spa (Cofresí) — Sep 3–7. NYC entertainment group DJs and nightlife for the holiday weekend on Puerto Plata's west coast.",
    date: "2026-09-03",
    endDate: "2026-09-07",
    time: "All day",
    location: "Puerto Plata",
    venue: "VIP Beach Lifestyles Resort and Spa",
    venueSlug: "vip-beach-lifestyles-resort",
    address: "Cofresí Beach #1, Puerto Plata 57000",
    lat: 19.793,
    lng: -70.715,
    category: "parties",
    categories: ["music"],
    format: "physical",
    trending: true,
    callForPricing: true,
    sourceUrl: "https://www.facebook.com/events/837847145240860",
    imageEmoji: "🎉",
  },
  {
    id: "sunset-laughter-club-cabarete",
    title: "Sunset Laughter Club",
    description:
      "Reina (Dominicated) hosts a 30-minute laughter club on Cabarete beach — Tuesdays from Jul 28 at 6:30 PM. Meet at the Ocean One beach entrance in the heart of Cabarete; bring water and wear comfortable clothes.",
    date: "2026-07-28",
    time: "6:30 PM – 7:30 PM",
    location: "Cabarete",
    venue: "Ocean One Cabarete",
    venueSlug: "ocean-one-cabarete",
    address: "Calle Principal, Cabarete 57000",
    lat: 19.7505,
    lng: -70.4082,
    category: "health-wellness",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 2,
    isFree: true,
    sourceUrl:
      "https://www.facebook.com/events/2243877129723142/2243877133056475",
    imageEmoji: "😊",
  },
];

const FALLBACK_EVENTS_ES: Event[] = [
  {
    id: "voyvoy-sunday-open-mic",
    title: "Open Mic y Jam Dominical en VOYVOY",
    description:
      "Música en vivo, open mic y jam en VOYVOY, Cabarete. Lester Grant abre la noche — trae tu instrumento o pide uno prestado. Ambiente relajado para tomar y cenar.",
    date: "2026-07-05",
    time: "5:00 PM – 11:00 PM",
    location: "Cabarete",
    venue: "VOYVOY Cabarete",
    venueSlug: "voyvoy-cabarete",
    category: "performances",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 0,
    imageEmoji: "🎤",
  },
  {
    id: "voyvoy-saturday-session",
    title: "Saturday Session en VOYVOY",
    description:
      "Noche de baile los sábados en VOYVOY con DJs invitados — reggaeton, dance club, sin cover. Un clásico de Cabarete para locales y visitantes.",
    date: "2026-07-11",
    time: "9:00 PM – 2:00 AM",
    location: "Cabarete",
    venue: "VOYVOY Cabarete",
    venueSlug: "voyvoy-cabarete",
    category: "parties",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6,
    imageEmoji: "🪩",
  },
  {
    id: "la-chabola-wednesday-open-mic",
    title: "Open Mic de miércoles en La Chabola",
    description:
      "Open mic los miércoles en La Chabola, Callejón de la Loma, Cabarete — músicos locales, pizza al horno de piedra y ambiente de barrio. Sube a cantar o solo escucha; de tarde a noche.",
    date: "2026-07-22",
    time: "8:00 PM – 12:00 AM",
    location: "Cabarete",
    venue: "La Chabola",
    venueSlug: "la-chabola-cabarete",
    address: "Callejón de la Loma, Cabarete 57000",
    lat: 19.7475887,
    lng: -70.4167516,
    category: "performances",
    categories: ["music"],
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 3,
    phone: "+18095435860",
    sourceUrl: "https://www.facebook.com/chabolacabaretee",
    imageEmoji: "🎤",
  },
  {
    id: "groundzero-domingos-pal-pueblo",
    title: "Domingos Pal Pueblo en Ground Zero",
    description:
      "Fiesta dominical en Ground Zero Discoteca — reggaetón, dembow, baile típico y urbano con DJs toda la noche, whisky a mitad de precio y hookah. En la carretera Puerto Plata–Sosúa frente al aeropuerto. Reserva mesa: 849-465-1313.",
    date: "2026-07-19",
    time: "9:00 PM – 4:00 AM",
    location: "Sosúa",
    venue: "Ground Zero Discoteca",
    venueSlug: "ground-zero-disco",
    address:
      "Km 18, Carretera Puerto Plata–Sosúa, frente al Aeropuerto Gregorio Luperón",
    lat: 19.76,
    lng: -70.565,
    category: "parties",
    categories: ["music", "dance"],
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 0,
    phone: "+18494651313",
    callForPricing: true,
    trending: true,
    sourceUrl: "https://www.instagram.com/groundzero_disco/p/DayWu9phE9R/",
    imageEmoji: "🪩",
  },
  {
    id: "lil-naay-2026-07-17",
    title: "Lil Naay en vivo en Disco Club",
    description:
      "El artista urbano dominicano Lil Naay en vivo en Disco Club (Depósitos de Brugal, Calle Duarte) — viernes 17 jul., 8–11 PM. Preventa RD$700 en todotickets.do (cargo por servicio incluido); ingreso con código QR electrónico.",
    date: "2026-07-17",
    time: "8:00 PM – 11:00 PM",
    location: "Puerto Plata",
    address: "Depósitos de Brugal, Calle Duarte",
    venue: "Disco Club",
    venueSlug: "disco-club-brugal",
    lat: 19.7966,
    lng: -70.6923,
    category: "concert",
    format: "physical",
    trending: true,
    isFree: false,
    admissionPrice: "RD$700",
    sourceUrl: "https://todotickets.do/events/lil-naay",
    ticketUrl: "https://todotickets.do/events/lil-naay",
    lineup: ["Lil Naay"],
    imageEmoji: "🎤",
  },
  {
    id: "lena-dardelet-aura-beach-club-2026-07-24",
    title: "Lena Dardelet × Pororó — De Aquí Pa'llá",
    description:
      "La cantautora franco-dominicana Lena Dardelet y Pororó abren su gira nacional De Aquí Pa'llá en Aura Beach Club, Calle Principal de Cabarete — viernes 24 jul., 8 PM AST. Entrada libre con RSVP en tix.do.",
    date: "2026-07-24",
    time: "8:00 PM",
    location: "Cabarete",
    venue: "Aura Beach Club Cabarete",
    venueSlug: "aura-beach-club-cabarete",
    address: "Calle Principal 5, Cabarete 57000",
    lat: 19.7500769,
    lng: -70.4070417,
    category: "concert",
    categories: ["music"],
    format: "physical",
    trending: true,
    isFree: true,
    phone: "+18297870140",
    sourceUrl:
      "https://www.bandsintown.com/e/108603887-lena-dardelet-at-aura-beach-club-cabarete",
    ticketUrl:
      "https://tix.do/event/PororoyLenaDardeletdeaquipallaencabarete-1",
    lineup: ["Lena Dardelet", "Pororó"],
    imageEmoji: "🎤",
  },
  {
    id: "cabarete-jazz-festival-2026",
    title: "Cabarete Jazz Festival 2026",
    description:
      "Segunda edición del Cabarete Jazz Festival (sáb. 6 jun.) — Alfredo Rodríguez, Cimafunk, Los Amigos Invisibles, iLe, Gia Fu y el saxofonista dominicano Sandy Gabriel. Jazz caribeño al aire libre producido por Cabarete Tango y Mishu Music; apertura a las 5 PM. Entradas en cabaretejazz.com.",
    date: "2026-06-06",
    time: "5:00 PM – 11:00 PM",
    location: "Cabarete",
    venue: "Cabarete Jazz Festival Grounds",
    lat: 19.770325,
    lng: -70.43824,
    category: "festivals",
    categories: ["concert", "music"],
    format: "physical",
    trending: true,
    sourceUrl: "https://www.cabaretejazz.com/",
    ticketUrl: "https://www.cabaretejazz.com/",
    lineup: [
      "Alfredo Rodríguez",
      "Cimafunk",
      "Los Amigos Invisibles",
      "iLe",
      "Gia Fu",
      "Sandy Gabriel",
    ],
    imageEmoji: "🎷",
  },
  {
    id: "jandy-ventura-legado-caballo-2026",
    title: "Jandy Ventura — El Legado del Caballo",
    description:
      "Jandy Ventura presenta el tributo de merengue a Johnny Ventura “El Legado del Caballo” en el centro de convenciones del Blue JackTar, Playa Dorada. Boletas en Supermercado José Luis, Tío Pan, Blue JackTar y La Locanda — Front Stage RD$5,000 · VIP RD$4,000 · General RD$2,500. Producción de GRAAN Events Planners.",
    date: "2026-07-30",
    time: "8:00 PM",
    location: "Puerto Plata",
    venue: "Blue JackTar Playa Dorada",
    venueSlug: "blue-jacktar-playa-dorada",
    address: "Centro de Convenciones, Playa Dorada",
    lat: 19.7703,
    lng: -70.6494,
    category: "concert",
    categories: ["music"],
    format: "physical",
    trending: true,
    admissionPrice: "RD$2,500–5,000",
    phone: "+18098898853",
    sourceUrl:
      "https://puertoplatadigital.com/puerto-plata-de-noche/el-legado-del-caballo-llega-a-puerto-plata",
    lineup: ["Jandy Ventura"],
    imageEmoji: "🎶",
  },
  {
    id: "rumble-in-paradise-12",
    title: "Rumble in Paradise 12",
    description:
      "Boxeo profesional en Playa Sosúa en Bar 39, con invitados especiales y firmas de autógrafos.",
    date: "2026-07-04",
    time: "5:00 PM – 9:00 PM",
    location: "Sosúa",
    venue: "Bar 39, Playa Sosúa",
    venueSlug: "bar-39-sosua",
    category: "sports",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/events/1614506996278636",
    imageEmoji: "🥊",
  },
  ...ATLETICOS_HOME_GAMES_ES,
  ...ASA_SURVIVAL_SERIES_ES,
  {
    id: "cabarete-classic-2026",
    title: "Cabarete Classic 2026",
    description:
      "Cuatro días de windsurf, kitesurf, wingfoil y foil en Playa Cabarete (16–19 jul.). La gran regata de deportes de viento del Caribe — competidores internacionales, clínicas y música nocturna en la playa.",
    date: "2026-07-16",
    endDate: "2026-07-19",
    time: "9:00 AM – 11:00 PM",
    location: "Cabarete",
    venue: "Playa Cabarete",
    venueSlug: "kite-beach",
    address: "Residencial Mañanero, Cabarete",
    category: "sports",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/events/4550504901861035/",
    imageEmoji: "🏄",
  },
  {
    id: "puerto-plata-golf-classic-2026",
    title: "Puerto Plata Golf Classic 2026",
    description:
      "13.ª edición del Puerto Plata Golf Classic de Ashonorte — torneo scramble por parejas en el campo de golf de Playa Dorada el sábado 18 de julio, con Night Putting Challenge y categorías con nombres de la costa norte (Puerto Plata, Sosúa, Cabarete, La Isabela). Inscripción US$210 vía el club; llama al +1 809 320 4262.",
    date: "2026-07-18",
    time: "7:00 AM – 9:00 PM",
    location: "Playa Dorada",
    venue: "Playa Dorada Golf Course",
    venueSlug: "playa-dorada-golf",
    address: "Playa Dorada, Puerto Plata",
    lat: 19.7635,
    lng: -70.6555,
    category: "sports",
    format: "physical",
    trending: true,
    admissionPrice: "US$210",
    phone: "+18093204262",
    sourceUrl: "https://playadoradagolf.com/en/event/puerto-plata-golf-classic/",
    imageEmoji: "⛳",
  },
  {
    id: "cac-games-surf-playa-encuentro-2026",
    title: "Surf Juegos CAC — Playa Encuentro",
    description:
      "Competencias de surf de los XXV Juegos Centroamericanos y del Caribe Santo Domingo 2026 en Playa Encuentro, Cabarete (25–29 jul.). Tabla corta, tabla larga y SUP Surf masculino y femenino — 71 atletas de 12 países en la ola emblemática de la costa norte. La mayoría de competencias CAC son gratis para el público; organizadores: +1 829 893 4214.",
    date: "2026-07-25",
    endDate: "2026-07-29",
    time: "8:00 AM – 6:00 PM",
    location: "Cabarete",
    venue: "Playa Encuentro",
    venueSlug: "playa-encuentro",
    address: "Playa Encuentro, Cabarete",
    lat: 19.7808,
    lng: -70.4825,
    category: "sports",
    format: "physical",
    trending: true,
    isFree: true,
    phone: "+18298934214",
    sourceUrl:
      "https://diamantedominicano.com/2026/05/playa-encuentro-en-cabarete-sera-sede-oficial-del-surf-en-los-juegos-centroamericanos-y-del-caribe-2026/",
    imageEmoji: "🏄",
  },
  {
    id: "puerto-plata-beach-soccer-2026",
    title: "Puerto Plata Beach Soccer 2026",
    description:
      "Segunda edición del Puerto Plata Beach Soccer en Playa Los Charamicos, Sosúa (21–23 ago.). Seis equipos de categoría superior y seis Sub-15 en tres jornadas familiares que impulsan el fútbol playa y el turismo deportivo de la costa norte. Entrada libre a la playa; consultas de equipos/info +1 809 586 6125.",
    date: "2026-08-21",
    endDate: "2026-08-23",
    time: "9:00 AM – 6:00 PM",
    location: "Sosúa",
    venue: "Playa Los Charamicos",
    venueSlug: "playa-los-charamicos",
    address: "Playa Los Charamicos, Sosúa",
    lat: 19.7542,
    lng: -70.5285,
    category: "sports",
    format: "physical",
    trending: true,
    isFree: true,
    phone: "+18095866125",
    sourceUrl:
      "https://puertoplatadigital.com/deportes/puerto-plata-beach-soccer-regresa-con-su-segunda-edicion-del-21-al-23-de-agosto-en-sosua",
    imageEmoji: "⚽",
  },
  {
    id: "sosua-10k-road-race-2026",
    title: "11.º Sosúa 10K",
    description:
      "11.ª edición del Sosúa 10K organizada por la Asociación de Desarrollo Sostenible de Sosúa (ADSS) — 10K por el centro de El Batey y 1K infantil (menores de 12). Salida el domingo 11 de octubre a las 6:45 AM desde Parque Las Flores; inscripción hasta el 7 de octubre a medianoche en sdctickets.do desde RD$500. Público espectador bienvenido. Info: +1 809 571 2100 · WhatsApp +1 829 546 7528.",
    date: "2026-10-11",
    time: "6:45 AM",
    location: "Sosúa",
    venue: "Parque Las Flores, El Batey",
    venueSlug: "el-batey-sosua",
    address: "Parque Las Flores, El Batey, Sosúa",
    lat: 19.7675,
    lng: -70.5115,
    category: "sports",
    format: "physical",
    trending: true,
    admissionPrice: "RD$500",
    phone: "+18095712100",
    sourceUrl: "https://sea-horse-ranch.com/sosua-10k-road-race/",
    ticketUrl: "https://www.sdctickets.do/detail/479",
    imageEmoji: "🏃",
  },
  {
    id: "puerto-plata-poker-experience-2026",
    title: "Puerto Plata Poker Experience (CLSOP)",
    description:
      "Festival de póker caribeño de diez días en el Coral Reef Casino, Sosúa Bay Center (28 ago.–6 sep.) — 15 torneos en dólares, cash games y un Main Event NLH con US$100,000 garantizados (buy-in US$900, reentradas ilimitadas). Serie frente al mar del circuito CLSOP.",
    date: "2026-08-28",
    endDate: "2026-09-06",
    time: "Ver programación",
    location: "Sosúa",
    venue: "Coral Reef Casino",
    address: "Dr. Alejo Martínez #1, Edif. Sosúa Bay Center, El Batey, Sosúa",
    lat: 19.7566,
    lng: -70.513,
    category: "festivals",
    format: "physical",
    trending: true,
    admissionPrice: "Main Event buy-in US$900",
    sourceUrl: "https://www.clsop.com/",
    ticketUrl: "https://www.clsop.com/",
    imageEmoji: "🃏",
  },
  {
    id: "aventurate-rd-2026",
    title: "Aventúrate RD 2026",
    description:
      "Segunda edición de Aventúrate RD, la feria de negocios de turismo de aventura y ecoturismo de la costa norte, en el Hotel Marién de Puerto Plata (2–4 sep.). Más de 60 expositores y 200+ compradores internacionales, con foros, ruedas de negocios y un cierre gastronómico en Sosúa. Organizada por AFEET RD y CDCT; inscripción en feriaaventuraterd.com.",
    date: "2026-09-02",
    endDate: "2026-09-04",
    time: "9:00 AM – 8:00 PM",
    location: "Puerto Plata",
    venue: "Hotel Marién",
    address: "Costa Dorada, Puerto Plata",
    lat: 19.8206,
    lng: -70.7079,
    category: "festivals",
    categories: ["culture"],
    format: "physical",
    trending: true,
    sourceUrl: "https://feriaaventuraterd.com/",
    ticketUrl: "https://feriaaventuraterd.com/",
    imageEmoji: "🌿",
  },
  {
    id: "sunset-cabarete-sessions-2026",
    title: "Sunset Cabarete Sessions",
    description:
      "Dos días de deep house frente al mar en Lux Beach Bar, Playa Cabarete (5–6 dic.) — kitesurf de día, transición al atardecer, DJs residentes y el invitado alemán Acid Pauli. Descalzo, +18, cerveza artesanal local; 2 PM–1 AM. Boletos desde US$16 en Ticketplus.",
    date: "2026-12-05",
    endDate: "2026-12-06",
    time: "2:00 PM – 1:00 AM",
    location: "Cabarete",
    venue: "Lux Beach Bar",
    address: "Playa Cabarete, Cabarete",
    lat: 19.7515,
    lng: -70.4098,
    category: "parties",
    categories: ["music"],
    format: "physical",
    trending: true,
    isFree: false,
    admissionPrice: "desde US$16",
    sourceUrl: "https://dominicana.myticketplus.com/events/sunset-cabarete-sessions",
    ticketUrl: "https://dominicana.myticketplus.com/events/sunset-cabarete-sessions",
    lineup: ["Acid Pauli"],
    imageEmoji: "🎧",
  },
  {
    id: "womens-reconnection-kite-camp-2026",
    title: "Women's Reconnection Kite Camp",
    description:
      "Campamento de kite de 7 noches para mujeres en la playa de Cabarete — flow, reconexión y sesiones de kite con la instructora IKO Ariadna Rabasa. Cupos early bird disponibles.",
    date: "2026-08-01",
    endDate: "2026-08-08",
    time: "8:00 AM – 8:00 PM",
    location: "Cabarete",
    venue: "Playa Cabarete",
    venueSlug: "kite-beach",
    category: "sports",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/events/1683911749456298/",
    imageEmoji: "🏄",
  },
  {
    id: "ingest-18th-annual-cabarete-butterfly-effect",
    title: "18.º Cabarete Butterfly Effect",
    description:
      "Festival de cinco días de deportes acuáticos para mujeres en Cabarete (7–11 jul): clínicas de SUP, yoga, limpieza de playa, crucero en catamarán y la travesía en remo por el río. Consulta el sitio oficial para horarios e inscripción.",
    date: "2026-07-07",
    endDate: "2026-07-11",
    time: "9:00 AM – 9:00 PM",
    location: "Cabarete",
    venue: "Kite Beach y Cabarete",
    address: "Carretera 5",
    venueSlug: "kite-beach",
    category: "festivals",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.cabaretebutterflyeffect.com/",
    imageEmoji: "🏄",
  },
  {
    id: "cabarete-pilates-reformer",
    title: "Clase Grupal de Pilates Reformer",
    description:
      "Sesiones grupales de Pilates Reformer en Cabarete con Rafaella Cirillo (mar y jue 9 AM). La dirección del estudio se confirma al reservar — DM o WhatsApp +1 809 460 5777. Código RC-pilates para la primera clase.",
    date: "2026-07-08",
    time: "9:00 AM – 10:00 AM",
    location: "Cabarete",
    venue: "Rafaella's Studio",
    category: "health-wellness",
    format: "physical",
    recurrence: "weekly",
    recurrenceDays: [2, 4],
    sourceUrl: "https://www.facebook.com/events/981611704653706/",
    imageEmoji: "🧘",
  },
  {
    id: "feria-artesanal-verano-2026",
    title: "Feria Artesanal Verano 2026",
    description:
      "La Feria Artesanal de Verano 2026 se lleva a cabo del 10 al 26 de julio en la Plaza Independencia (el Parque Central de Puerto Plata). El evento reúne a más de 120 artesanos locales y se encuentra abierto todos los días en un horario de 8:00 a.m. a 9:00 p.m. Allí podrás disfrutar de piezas hechas a mano, exhibiciones culturales, arte, souvenirs y caretas de cabezudos. Esta iniciativa tiene como objetivo impulsar el talento de los artistas locales y acercar la artesanía dominicana a visitantes y residentes.",
    date: "2026-07-10",
    endDate: "2026-07-26",
    time: "8:00 AM – 9:00 PM",
    location: "Puerto Plata",
    venue: "Plaza Independencia (Parque Central)",
    venueSlug: "plaza-independencia",
    address: "Calle San Felipe, Puerto Plata",
    category: "festivals",
    categories: ["culture"],
    format: "physical",
    trending: true,
    isFree: true,
    sourceUrl: "https://www.facebook.com/share/18vHNaoe69/",
    imageEmoji: "🎨",
  },
  {
    id: "puerto-plata-carnaval-2026",
    title: "Carnaval Puerto Plata 2026",
    description:
      "Carnaval Puerto Plata 2026 en el Malecón — desfiles dominicales cada febrero (1, 8, 15 y 22 feb.) culminando con el Gran Desfile Final el 1 de marzo en el Anfiteatro La Puntilla. Caretas taimáscaro, comparsas y cultura folclórica dominicana.",
    date: "2026-02-01",
    endDate: "2026-03-01",
    time: "2:00 PM – 8:00 PM",
    location: "Puerto Plata",
    venue: "Malecón de Puerto Plata y Anfiteatro La Puntilla",
    venueSlug: "malecon-puerto-plata",
    category: "festivals",
    format: "physical",
    trending: true,
    sourceUrl:
      "https://sea-horse-ranch.com/carnival-celebrations-in-the-dominican-republic/",
    imageEmoji: "🎭",
  },
  {
    id: "malecon-morning-wellness-walk",
    title: "Caminata matutina de wellness en el Malecón",
    description:
      "Caminantes y corredores temprano en el Malecón de Puerto Plata — brisa marina, grupos de estiramiento y ritual diario de bienestar en el paseo marítimo.",
    date: "2026-01-01",
    time: "6:00 AM – 8:00 AM",
    location: "Puerto Plata",
    venue: "Malecón de Puerto Plata",
    venueSlug: "malecon-puerto-plata",
    category: "health-wellness",
    format: "physical",
    recurrence: "daily",
    imageEmoji: "🚶",
  },
  {
    id: "sancocho-sabados-pingui",
    title: "Sancocho Sábados en Pingüi",
    description:
      "¡Los sábados tienen sabor a tradición! Disfruta de nuestro sancocho frente al mar en Playa El Pueblito en Pingüi Bar. Reúne a tus amigos y familiares para compartir una tarde de comida dominicana con vista al océano (12–4 PM).",
    date: "2026-07-11",
    time: "12:00 PM – 4:00 PM",
    location: "Puerto Plata",
    venue: "Pingüi Bar Restaurant & Piña Colada House",
    venueSlug: "pingui-bar",
    address: "C. B, Puerto Plata 57000",
    lat: 19.773903,
    lng: -70.652704,
    category: "food-drinks",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6,
    sourceUrl:
      "https://www.facebook.com/events/1547520700301499/1547522116968024/",
    imageEmoji: "🍲",
  },
  {
    id: "el-colibri-karaoke-battle-2026",
    title: "Karaoke Battle El Colibri — Jueves",
    description:
      "Karaoke los jueves en El Colibri Hotel, Sosúa (7 PM–medianoche). Únete al Karaoke Battle de 8 semanas — $20,000 en premios (2 jul–3 sep 2026). Los concursantes deben asistir todos los jueves para seguir elegibles. Inscripción por WhatsApp: +1 917-523-7259.",
    date: "2026-07-02",
    endDate: "2026-09-03",
    time: "7:00 PM – 12:00 AM",
    location: "Sosúa",
    venue: "El Colibri Hotel",
    venueSlug: "el-colibri-hotel",
    address: "141 Pedro Clisante, Sosúa 57600",
    lat: 19.7545,
    lng: -70.519,
    category: "music",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 4,
    trending: true,
    sourceUrl: "https://www.elcolibriresort.com/",
    imageEmoji: "🎤",
  },
  {
    id: "inicio-del-campamento-pp-2026",
    title: "Inicio del Campamento",
    description:
      "Inicio de campamento deportivo en el histórico San Felipe, Puerto Plata — organizado por Sin pelos en la lengua. Consulta el evento en Facebook para inscripción.",
    date: "2026-07-10",
    time: "5:00 PM – 8:00 PM",
    location: "Puerto Plata",
    venue: "San Felipe de Puerto Plata",
    venueSlug: "fortaleza-san-felipe",
    category: "sports",
    format: "physical",
    sourceUrl: "https://www.facebook.com/events/1017381540870816/",
    imageEmoji: "⚽",
  },
  {
    id: "silent-run-5k-2026-07-25",
    title: "Silent Run 5K — Malecón Puerto Plata",
    description:
      "Carrera 5K inmersiva por el Malecón de Puerto Plata con audífonos sincronizados a un DJ en vivo — organizada por Aleva Experiences. Punto de encuentro: Victrola 037 Arte Café; neon after-party, rifas y premios al final. Entradas desde RD$950 en boletu.com (fases agotadas — únete a la lista de espera).",
    date: "2026-07-25",
    time: "6:00 AM",
    location: "Puerto Plata",
    venue: "Victrola 037 Arte Café",
    venueSlug: "victrola-037",
    address: "Av. Gral. Gregorio Luperón esq. Padre Castellanos, Puerto Plata 57000",
    lat: 19.7975,
    lng: -70.6928,
    category: "sports",
    categories: ["health-wellness"],
    format: "physical",
    trending: true,
    isFree: false,
    admissionPrice: "RD$950–1,100",
    sourceUrl: "https://www.facebook.com/events/1290779933223443",
    ticketUrl: "https://boletu.com/event/silent-run-5k",
    imageEmoji: "🎧",
  },
  {
    id: "piscinazo-pop-urbano-037-2026-08-02",
    title: "Piscinazo POP Urbano 037 — 1ra Edición",
    description:
      "Primer piscinazo 2026 de Pop Urbano 037 bajo el sello Black & White Music and Entertainment — cinco cantantes de Puerto Plata en escena. Lugar por confirmar en San Felipe; sigue el evento de Facebook para votar el lineup y más detalles.",
    date: "2026-08-02",
    time: "10:00 AM",
    location: "Puerto Plata",
    venue: "San Felipe de Puerto Plata",
    category: "parties",
    categories: ["music"],
    format: "physical",
    trending: true,
    callForPricing: true,
    sourceUrl: "https://www.facebook.com/events/979095458299610",
    imageEmoji: "🏊",
  },
  {
    id: "los-event-trilogy-2026-09-03",
    title: "LOS Event — Fin de semana Labor Day con Trilogy",
    description:
      "Fiesta de varios días por Labor Day 2026 de Trilogy World en VIP Beach Lifestyles Resort and Spa (Cofresí) — 3–7 sep. DJs y vida nocturna del grupo de entretenimiento de NYC para el feriado en la costa oeste de Puerto Plata.",
    date: "2026-09-03",
    endDate: "2026-09-07",
    time: "Todo el día",
    location: "Puerto Plata",
    venue: "VIP Beach Lifestyles Resort and Spa",
    venueSlug: "vip-beach-lifestyles-resort",
    address: "Cofresí Beach #1, Puerto Plata 57000",
    lat: 19.793,
    lng: -70.715,
    category: "parties",
    categories: ["music"],
    format: "physical",
    trending: true,
    callForPricing: true,
    sourceUrl: "https://www.facebook.com/events/837847145240860",
    imageEmoji: "🎉",
  },
  {
    id: "sunset-laughter-club-cabarete",
    title: "Sunset Laughter Club",
    description:
      "Reina (Dominicated) organiza un club de risa de 30 minutos en la playa de Cabarete — martes desde el 28 jul a las 6:30 PM. Encuentro en la entrada de playa de Ocean One en el corazón de Cabarete; lleva agua y ropa cómoda.",
    date: "2026-07-28",
    time: "6:30 PM – 7:30 PM",
    location: "Cabarete",
    venue: "Ocean One Cabarete",
    venueSlug: "ocean-one-cabarete",
    address: "Calle Principal, Cabarete 57000",
    lat: 19.7505,
    lng: -70.4082,
    category: "health-wellness",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 2,
    isFree: true,
    sourceUrl:
      "https://www.facebook.com/events/2243877129723142/2243877133056475",
    imageEmoji: "😊",
  },
];

function getWorldCupEvents(locale: Locale): Event[] {
  if (locale === "es") return EL_CAREY_WC2026_EVENTS_ES;
  if (locale === "fr") return EL_CAREY_WC2026_EVENTS_FR;
  return EL_CAREY_WC2026_EVENTS_EN;
}

export function getFallbackEvents(locale: Locale = "en"): Event[] {
  const base =
    locale === "es"
      ? FALLBACK_EVENTS_ES
      : locale === "fr"
        ? FALLBACK_EVENTS_FR
        : FALLBACK_EVENTS_EN;
  const merged = [
    ...getRecurringEvents(locale),
    ...base,
    ...getWorldCupEvents(locale),
  ];
  return materializeEventDates(filterRemovedSeedEvents(merged)).map(
    withResolvedCategories,
  );
}

/** Lookup before date materialization — keeps expired one-offs resolvable for share links. */
export function getFallbackEventById(
  id: string,
  locale: Locale = "en",
): Event | undefined {
  const base =
    locale === "es"
      ? FALLBACK_EVENTS_ES
      : locale === "fr"
        ? FALLBACK_EVENTS_FR
        : FALLBACK_EVENTS_EN;
  const merged = filterRemovedSeedEvents([
    ...getRecurringEvents(locale),
    ...base,
    ...getWorldCupEvents(locale),
  ]);
  return merged.find((e) => e.id === id);
}

export function getFallbackForCategory(
  category: EventCategory,
  locale: Locale = "en",
): Event[] {
  return getFallbackEvents(locale).filter((e) => eventInCategory(e, category));
}
