import type { Event } from "./types";
import { ATLETICOS_HOME_GAMES_FR } from "./atleticos-summer-league-2026";
import { ASA_SURVIVAL_SERIES_FR } from "./asa-survival-series-2026";

/** French translations of curated North Coast events. */
export const FALLBACK_EVENTS_FR: Event[] = [
  {
    id: "voyvoy-sunday-open-mic",
    title: "Open mic & jam du dimanche à VOYVOY",
    description:
      "Musique live, open mic et jam à VOYVOY, Cabarete. Lester Grant lance la soirée — apportez un instrument ou empruntez-en un. Ambiance détendue pour boire et dîner.",
    date: "2026-07-05",
    time: "5:00 PM – 11:00 PM",
    location: "Cabarete",
    venue: "VOYVOY Cabarete",
    venueSlug: "voyvoy-cabarete",
    category: "performances",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 0,
    imageEmoji: "🎤",
  },
  {
    id: "voyvoy-saturday-session",
    title: "Saturday Session à VOYVOY",
    description:
      "Soirée danse le samedi à VOYVOY avec DJs invités — reggaeton, club, sans cover. Un incontournable de Cabarete pour locaux et visiteurs.",
    date: "2026-07-11",
    time: "9:00 PM – 2:00 AM",
    location: "Cabarete",
    venue: "VOYVOY Cabarete",
    venueSlug: "voyvoy-cabarete",
    category: "parties",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6,
    imageEmoji: "🪩",
  },
  {
    id: "la-chabola-wednesday-open-mic",
    title: "Open mic du mercredi à La Chabola",
    description:
      "Open mic le mercredi à La Chabola, Callejón de la Loma, Cabarete — musiciens locaux, pizza au four à pierre et ambiance de quartier. Montez sur scène ou écoutez ; de la fin d'après-midi jusqu'à la nuit.",
    date: "2026-07-22",
    time: "8:00 PM – 12:00 AM",
    location: "Cabarete",
    venue: "La Chabola",
    venueSlug: "la-chabola-cabarete",
    address: "Callejón de la Loma, Cabarete 57000",
    lat: 19.7475887,
    lng: -70.4167516,
    category: "performances",
    categories: ["music"],
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 3,
    phone: "+18095435860",
    sourceUrl: "https://www.facebook.com/chabolacabaretee",
    imageEmoji: "🎤",
  },
  {
    id: "groundzero-domingos-pal-pueblo",
    title: "Domingos Pal Pueblo au Ground Zero",
    description:
      "Soirées du dimanche au Ground Zero Discoteca — reggaeton, dembow, baile típico et urbain avec DJs toute la nuit, whisky à moitié prix et chicha. Sur la route Puerto Plata–Sosúa face à l'aéroport. Réservez une table : 849-465-1313.",
    date: "2026-07-19",
    time: "9:00 PM – 4:00 AM",
    location: "Sosúa",
    venue: "Ground Zero Discoteca",
    venueSlug: "ground-zero-disco",
    address:
      "Km 18, Carretera Puerto Plata–Sosúa, frente al Aeropuerto Gregorio Luperón",
    lat: 19.76,
    lng: -70.565,
    category: "parties",
    categories: ["music", "dance"],
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 0,
    phone: "+18494651313",
    callForPricing: true,
    trending: true,
    sourceUrl: "https://www.instagram.com/groundzero_disco/p/DayWu9phE9R/",
    imageEmoji: "🪩",
  },
  {
    id: "lil-naay-2026-07-17",
    title: "Lil Naay en live au Disco Club",
    description:
      "La star urbaine dominicaine Lil Naay en live au Disco Club (Depósitos de Brugal, Calle Duarte) — vendredi 17 juil., 20 h–23 h. Prévente RD$700 sur todotickets.do (frais de service inclus) ; entrée par billet QR électronique.",
    date: "2026-07-17",
    time: "8:00 PM – 11:00 PM",
    location: "Puerto Plata",
    address: "Depósitos de Brugal, Calle Duarte",
    venue: "Disco Club",
    venueSlug: "disco-club-brugal",
    lat: 19.7966,
    lng: -70.6923,
    category: "concert",
    format: "physical",
    trending: true,
    isFree: false,
    admissionPrice: "RD$700",
    sourceUrl: "https://todotickets.do/events/lil-naay",
    ticketUrl: "https://todotickets.do/events/lil-naay",
    lineup: ["Lil Naay"],
    imageEmoji: "🎤",
  },
  {
    id: "lena-dardelet-aura-beach-club-2026-07-24",
    title: "Lena Dardelet × Pororó — De Aquí Pa'llá",
    description:
      "La chanteuse franco-dominicaine Lena Dardelet et Pororó ouvrent leur tournée nationale De Aquí Pa'llá à l'Aura Beach Club, Calle Principal de Cabarete — vendredi 24 juil., 20 h AST. Entrée libre avec RSVP sur tix.do.",
    date: "2026-07-24",
    time: "8:00 PM",
    location: "Cabarete",
    venue: "Aura Beach Club Cabarete",
    venueSlug: "aura-beach-club-cabarete",
    address: "Calle Principal 5, Cabarete 57000",
    lat: 19.7500769,
    lng: -70.4070417,
    category: "concert",
    categories: ["music"],
    format: "physical",
    trending: true,
    isFree: true,
    phone: "+18297870140",
    sourceUrl:
      "https://www.bandsintown.com/e/108603887-lena-dardelet-at-aura-beach-club-cabarete",
    ticketUrl:
      "https://tix.do/event/PororoyLenaDardeletdeaquipallaencabarete-1",
    lineup: ["Lena Dardelet", "Pororó"],
    imageEmoji: "🎤",
  },
  {
    id: "cabarete-jazz-festival-2026",
    title: "Cabarete Jazz Festival 2026",
    description:
      "Deuxième édition du Cabarete Jazz Festival (sam. 6 juin) — Alfredo Rodríguez, Cimafunk, Los Amigos Invisibles, iLe, Gia Fu et le saxophoniste dominicain Sandy Gabriel. Jazz caribéen en plein air produit par Cabarete Tango et Mishu Music ; ouverture à 17 h. Billets sur cabaretejazz.com.",
    date: "2026-06-06",
    time: "5:00 PM – 11:00 PM",
    location: "Cabarete",
    venue: "Cabarete Jazz Festival Grounds",
    lat: 19.770325,
    lng: -70.43824,
    category: "festivals",
    categories: ["concert", "music"],
    format: "physical",
    trending: true,
    sourceUrl: "https://www.cabaretejazz.com/",
    ticketUrl: "https://www.cabaretejazz.com/",
    lineup: [
      "Alfredo Rodríguez",
      "Cimafunk",
      "Los Amigos Invisibles",
      "iLe",
      "Gia Fu",
      "Sandy Gabriel",
    ],
    imageEmoji: "🎷",
  },
  {
    id: "jandy-ventura-legado-caballo-2026",
    title: "Jandy Ventura — El Legado del Caballo",
    description:
      "Jandy Ventura présente l'hommage merengue à Johnny Ventura « El Legado del Caballo » au centre de congrès du Blue JackTar, Playa Dorada. Billets en vente locale chez Supermercado José Luis, Tío Pan, Blue JackTar et La Locanda — Front Stage RD$5 000 · VIP RD$4 000 · Général RD$2 500. Production GRAAN Events Planners.",
    date: "2026-07-30",
    time: "8:00 PM",
    location: "Puerto Plata",
    venue: "Blue JackTar Playa Dorada",
    venueSlug: "blue-jacktar-playa-dorada",
    address: "Centro de Convenciones, Playa Dorada",
    lat: 19.7703,
    lng: -70.6494,
    category: "concert",
    categories: ["music"],
    format: "physical",
    trending: true,
    admissionPrice: "RD$2,500–5,000",
    phone: "+18098898853",
    sourceUrl:
      "https://puertoplatadigital.com/puerto-plata-de-noche/el-legado-del-caballo-llega-a-puerto-plata",
    lineup: ["Jandy Ventura"],
    imageEmoji: "🎶",
  },
  {
    id: "rumble-in-paradise-12",
    title: "Rumble in Paradise 12",
    description:
      "Boxe professionnelle sur la plage de Sosúa au Bar 39, avec invités spéciaux et séances d'autographes.",
    date: "2026-07-04",
    time: "5:00 PM – 9:00 PM",
    location: "Sosúa",
    venue: "Bar 39, Playa Sosúa",
    venueSlug: "bar-39-sosua",
    category: "sports",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/events/1614506996278636",
    imageEmoji: "🥊",
  },
  ...ATLETICOS_HOME_GAMES_FR,
  ...ASA_SURVIVAL_SERIES_FR,
  {
    id: "cabarete-classic-2026",
    title: "Cabarete Classic 2026",
    description:
      "Quatre jours de windsurf, kitesurf, wingfoil et foil sur la plage de Cabarete (16–19 juil.). La grande régate des sports de vent des Caraïbes — compétiteurs internationaux, cliniques et musique le soir sur la plage.",
    date: "2026-07-16",
    endDate: "2026-07-19",
    time: "9:00 AM – 11:00 PM",
    location: "Cabarete",
    venue: "Playa Cabarete",
    venueSlug: "kite-beach",
    address: "Residencial Mañanero, Cabarete",
    category: "sports",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/events/4550504901861035/",
    imageEmoji: "🏄",
  },
  {
    id: "puerto-plata-golf-classic-2026",
    title: "Puerto Plata Golf Classic 2026",
    description:
      "13e édition du Puerto Plata Golf Classic d'Ashonorte — tournoi scramble en paires au Playa Dorada Golf Course le samedi 18 juillet, avec Night Putting Challenge et catégories aux noms de la côte nord (Puerto Plata, Sosúa, Cabarete, La Isabela). Inscription US$210 via le club ; appelez le +1 809 320 4262.",
    date: "2026-07-18",
    time: "7:00 AM – 9:00 PM",
    location: "Playa Dorada",
    venue: "Playa Dorada Golf Course",
    venueSlug: "playa-dorada-golf",
    address: "Playa Dorada, Puerto Plata",
    lat: 19.7635,
    lng: -70.6555,
    category: "sports",
    format: "physical",
    trending: true,
    admissionPrice: "US$210",
    phone: "+18093204262",
    sourceUrl: "https://playadoradagolf.com/en/event/puerto-plata-golf-classic/",
    imageEmoji: "⛳",
  },
  {
    id: "cac-games-surf-playa-encuentro-2026",
    title: "Surf Jeux CAC — Playa Encuentro",
    description:
      "Épreuves de surf des XXVe Jeux d'Amérique centrale et des Caraïbes Santo Domingo 2026 à Playa Encuentro, Cabarete (25–29 juil.). Shortboard, longboard et SUP Surf hommes et femmes — 71 athlètes de 12 pays sur la vague phare de la côte nord. La plupart des épreuves CAC sont gratuites pour le public ; organisateurs : +1 829 893 4214.",
    date: "2026-07-25",
    endDate: "2026-07-29",
    time: "8:00 AM – 6:00 PM",
    location: "Cabarete",
    venue: "Playa Encuentro",
    venueSlug: "playa-encuentro",
    address: "Playa Encuentro, Cabarete",
    lat: 19.7808,
    lng: -70.4825,
    category: "sports",
    format: "physical",
    trending: true,
    isFree: true,
    phone: "+18298934214",
    sourceUrl:
      "https://diamantedominicano.com/2026/05/playa-encuentro-en-cabarete-sera-sede-oficial-del-surf-en-los-juegos-centroamericanos-y-del-caribe-2026/",
    imageEmoji: "🏄",
  },
  {
    id: "puerto-plata-beach-soccer-2026",
    title: "Puerto Plata Beach Soccer 2026",
    description:
      "Deuxième édition du Puerto Plata Beach Soccer à Playa Los Charamicos, Sosúa (21–23 août). Six équipes seniors et six U-15 sur trois journées familiales pour promouvoir le beach soccer et le tourisme sportif de la côte nord. Accès libre à la plage ; infos équipes +1 809 586 6125.",
    date: "2026-08-21",
    endDate: "2026-08-23",
    time: "9:00 AM – 6:00 PM",
    location: "Sosúa",
    venue: "Playa Los Charamicos",
    venueSlug: "playa-los-charamicos",
    address: "Playa Los Charamicos, Sosúa",
    lat: 19.7542,
    lng: -70.5285,
    category: "sports",
    format: "physical",
    trending: true,
    isFree: true,
    phone: "+18095866125",
    sourceUrl:
      "https://puertoplatadigital.com/deportes/puerto-plata-beach-soccer-regresa-con-su-segunda-edicion-del-21-al-23-de-agosto-en-sosua",
    imageEmoji: "⚽",
  },
  {
    id: "sosua-10k-road-race-2026",
    title: "11e Sosúa 10K",
    description:
      "11e édition du Sosúa 10K organisée par l'Association pour le développement durable de Sosúa (ADSS) — 10K dans le centre d'El Batey et 1K enfants (moins de 12 ans). Départ dimanche 11 octobre à 6 h 45 au Parque Las Flores ; inscription jusqu'au 7 octobre à minuit sur sdctickets.do dès RD$500. Spectateurs bienvenus. Infos : +1 809 571 2100 · WhatsApp +1 829 546 7528.",
    date: "2026-10-11",
    time: "6:45 AM",
    location: "Sosúa",
    venue: "Parque Las Flores, El Batey",
    venueSlug: "el-batey-sosua",
    address: "Parque Las Flores, El Batey, Sosúa",
    lat: 19.7675,
    lng: -70.5115,
    category: "sports",
    format: "physical",
    trending: true,
    admissionPrice: "RD$500",
    phone: "+18095712100",
    sourceUrl: "https://sea-horse-ranch.com/sosua-10k-road-race/",
    ticketUrl: "https://www.sdctickets.do/detail/479",
    imageEmoji: "🏃",
  },
  {
    id: "puerto-plata-poker-experience-2026",
    title: "Puerto Plata Poker Experience (CLSOP)",
    description:
      "Festival de poker caribéen de dix jours au Coral Reef Casino, Sosúa Bay Center (28 août–6 sept.) — 15 tournois en dollars, cash games et un Main Event NLH garanti à 100 000 US$ (buy-in 900 US$, rentrées illimitées). Série en bord de mer du circuit CLSOP.",
    date: "2026-08-28",
    endDate: "2026-09-06",
    time: "Voir le programme",
    location: "Sosúa",
    venue: "Coral Reef Casino",
    address: "Dr. Alejo Martínez #1, Edif. Sosúa Bay Center, El Batey, Sosúa",
    lat: 19.7566,
    lng: -70.513,
    category: "festivals",
    format: "physical",
    trending: true,
    admissionPrice: "Main Event buy-in 900 US$",
    sourceUrl: "https://www.clsop.com/",
    ticketUrl: "https://www.clsop.com/",
    imageEmoji: "🃏",
  },
  {
    id: "aventurate-rd-2026",
    title: "Aventúrate RD 2026",
    description:
      "Deuxième édition d'Aventúrate RD, le salon professionnel du tourisme d'aventure et de l'écotourisme de la côte nord, à l'Hôtel Marién de Puerto Plata (2–4 sept.). Plus de 60 exposants et 200+ acheteurs internationaux, avec forums, rendez-vous d'affaires et une clôture gastronomique à Sosúa. Organisé par AFEET RD et CDCT ; inscription sur feriaaventuraterd.com.",
    date: "2026-09-02",
    endDate: "2026-09-04",
    time: "9:00 AM – 8:00 PM",
    location: "Puerto Plata",
    venue: "Hotel Marién",
    address: "Costa Dorada, Puerto Plata",
    lat: 19.8206,
    lng: -70.7079,
    category: "festivals",
    categories: ["culture"],
    format: "physical",
    trending: true,
    sourceUrl: "https://feriaaventuraterd.com/",
    ticketUrl: "https://feriaaventuraterd.com/",
    imageEmoji: "🌿",
  },
  {
    id: "sunset-cabarete-sessions-2026",
    title: "Sunset Cabarete Sessions",
    description:
      "Deux jours de deep house en bord de mer au Lux Beach Bar, Playa Cabarete (5–6 déc.) — kitesurf le jour, transition au coucher du soleil, DJs résidents et l'invité allemand Acid Pauli. Pieds nus, +18, bière artisanale locale ; 14 h–1 h. Billets dès 16 US$ sur Ticketplus.",
    date: "2026-12-05",
    endDate: "2026-12-06",
    time: "2:00 PM – 1:00 AM",
    location: "Cabarete",
    venue: "Lux Beach Bar",
    address: "Playa Cabarete, Cabarete",
    lat: 19.7515,
    lng: -70.4098,
    category: "parties",
    categories: ["music"],
    format: "physical",
    trending: true,
    isFree: false,
    admissionPrice: "dès 16 US$",
    sourceUrl: "https://dominicana.myticketplus.com/events/sunset-cabarete-sessions",
    ticketUrl: "https://dominicana.myticketplus.com/events/sunset-cabarete-sessions",
    lineup: ["Acid Pauli"],
    imageEmoji: "🎧",
  },
  {
    id: "womens-reconnection-kite-camp-2026",
    title: "Women's Reconnection Kite Camp",
    description:
      "Camp de kite de 7 nuits pour femmes en bord de mer à Cabarete — flow, reconnexion et sessions kite avec l'instructrice IKO Ariadna Rabasa. Places early bird disponibles.",
    date: "2026-08-01",
    endDate: "2026-08-08",
    time: "8:00 AM – 8:00 PM",
    location: "Cabarete",
    venue: "Playa Cabarete",
    venueSlug: "kite-beach",
    category: "sports",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/events/1683911749456298/",
    imageEmoji: "🏄",
  },
  {
    id: "cabarete-pilates-reformer",
    title: "Cours collectif Pilates Reformer",
    description:
      "Cours collectifs de Pilates Reformer à Cabarete avec Rafaella Cirillo (mar. et jeu. 9 h). L'adresse du studio est communiquée à la réservation — DM ou WhatsApp +1 809 460 5777. Code RC-pilates pour le premier cours.",
    date: "2026-07-08",
    time: "9:00 AM – 10:00 AM",
    location: "Cabarete",
    venue: "Rafaella's Studio",
    category: "health-wellness",
    format: "physical",
    recurrence: "weekly",
    recurrenceDays: [2, 4],
    sourceUrl: "https://www.facebook.com/events/981611704653706/",
    imageEmoji: "🧘",
  },
  {
    id: "feria-artesanal-verano-2026",
    title: "Feria Artesanal Verano 2026",
    description:
      "La foire artisanale d'été 2026 se tient du 10 au 26 juillet sur la Plaza Independencia (le parc central de Puerto Plata). Plus de 120 artisans locaux y exposent tous les jours de 8 h à 21 h : pièces faites main, expositions culturelles, art, souvenirs et masques de cabezudos. L'initiative vise à mettre en valeur les artistes locaux et rapprocher l'artisanat dominicain des visiteurs et des résidents.",
    date: "2026-07-10",
    endDate: "2026-07-26",
    time: "8:00 AM – 9:00 PM",
    location: "Puerto Plata",
    venue: "Plaza Independencia (Parque Central)",
    venueSlug: "plaza-independencia",
    address: "Calle San Felipe, Puerto Plata",
    category: "festivals",
    categories: ["culture"],
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/share/18vHNaoe69/",
    imageEmoji: "🎨",
  },
  {
    id: "puerto-plata-carnaval-2026",
    title: "Carnaval Puerto Plata 2026",
    description:
      "Carnaval Puerto Plata 2026 sur le Malecón — parades dominicales chaque dimanche de février (1, 8, 15 et 22 fév.) culminant avec le Gran Desfile Final le 1er mars à l'Anfiteatro La Puntilla. Masques taimáscaro, comparsas et culture folklorique dominicaine.",
    date: "2026-02-01",
    endDate: "2026-03-01",
    time: "2:00 PM – 8:00 PM",
    location: "Puerto Plata",
    venue: "Malecón de Puerto Plata et Anfiteatro La Puntilla",
    venueSlug: "malecon-puerto-plata",
    category: "festivals",
    format: "physical",
    trending: true,
    sourceUrl:
      "https://sea-horse-ranch.com/carnival-celebrations-in-the-dominican-republic/",
    imageEmoji: "🎭",
  },
  {
    id: "malecon-morning-wellness-walk",
    title: "Marche wellness matinale sur le Malecón",
    description:
      "Marcheurs et joggeurs tôt le matin sur le Malecón de Puerto Plata — brise marine, groupes d'étirement et rituel de bienêtre quotidien sur la promenade.",
    date: "2026-01-01",
    time: "6:00 AM – 8:00 AM",
    location: "Puerto Plata",
    venue: "Malecón de Puerto Plata",
    venueSlug: "malecon-puerto-plata",
    category: "health-wellness",
    format: "physical",
    recurrence: "daily",
    imageEmoji: "🚶",
  },
  {
    id: "ingest-18th-annual-cabarete-butterfly-effect",
    title: "18e Cabarete Butterfly Effect",
    description:
      "Festival femmes et sports nautiques sur cinq jours à Cabarete (7–11 juil.) : SUP, yoga, nettoyage de plage, croisière catamaran et paddle sur la rivière. Programme et inscription sur le site officiel.",
    date: "2026-07-07",
    endDate: "2026-07-11",
    time: "9:00 AM – 9:00 PM",
    location: "Cabarete",
    venue: "Kite Beach et Cabarete",
    address: "Carretera 5",
    venueSlug: "kite-beach",
    category: "festivals",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.cabaretebutterflyeffect.com/",
    imageEmoji: "🏄",
  },
  {
    id: "sancocho-sabados-pingui",
    title: "Sancocho du samedi chez Pingüi",
    description:
      "Le samedi goûte la tradition chez Pingüi Bar — dégustez un sancocho face à la mer à Playa El Pueblito. Réunissez amis et famille pour un après-midi de cuisine dominicaine avec vue sur l'océan (12 h–16 h).",
    date: "2026-07-11",
    time: "12:00 PM – 4:00 PM",
    location: "Puerto Plata",
    venue: "Pingüi Bar Restaurant & Piña Colada House",
    address: "C. B, Puerto Plata 57000",
    lat: 19.773903,
    lng: -70.652704,
    category: "food-drinks",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6,
    sourceUrl:
      "https://www.facebook.com/events/1547520700301499/1547522116968024/",
    imageEmoji: "🍲",
  },
  {
    id: "el-colibri-karaoke-battle-2026",
    title: "Karaoke Battle El Colibri — Jeudis",
    description:
      "Soirées karaoké le jeudi à l'El Colibri Hotel, Sosúa (19 h–minuit). Participez au Karaoke Battle sur 8 semaines — 20 000 $ de prix (2 juil.–3 sept. 2026). Les candidats doivent être présents chaque jeudi pour rester éligibles. Inscription par WhatsApp : +1 917-523-7259.",
    date: "2026-07-02",
    endDate: "2026-09-03",
    time: "7:00 PM – 12:00 AM",
    location: "Sosúa",
    venue: "El Colibri Hotel",
    venueSlug: "el-colibri-hotel",
    address: "141 Pedro Clisante, Sosúa 57600",
    lat: 19.7545,
    lng: -70.519,
    category: "music",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 4,
    trending: true,
    sourceUrl: "https://www.elcolibriresort.com/",
    imageEmoji: "🎤",
  },
  {
    id: "inicio-del-campamento-pp-2026",
    title: "Ouverture du camp sportif",
    description:
      "Lancement d'un camp sportif dans le quartier historique de San Felipe, Puerto Plata — organisé par Sin pelos en la lengua. Consultez l'événement Facebook pour l'inscription.",
    date: "2026-07-10",
    time: "5:00 PM – 8:00 PM",
    location: "Puerto Plata",
    venue: "San Felipe de Puerto Plata",
    venueSlug: "fortaleza-san-felipe",
    category: "sports",
    format: "physical",
    sourceUrl: "https://www.facebook.com/events/1017381540870816/",
    imageEmoji: "⚽",
  },
];
