import type { Event } from "./types";

/** French translations of curated North Coast events. */
export const FALLBACK_EVENTS_FR: Event[] = [
  {
    id: "sosua-beach-jam",
    title: "Musique live sur la plage de Sosúa",
    description:
      "Sessions hebdomadaires au coucher du soleil avec groupes locaux et DJs. Le genre d'événement qu'on découvre par un ami.",
    date: "2026-07-05",
    time: "6:00 PM",
    location: "Sosúa",
    venue: "Playa Sosúa",
    category: "music",
    format: "physical",
    trending: true,
    recurrence: "weekly",
    recurrenceDay: 0,
    imageEmoji: "🎸",
  },
  {
    id: "voyvoy-sunday-open-mic",
    title: "Open mic & jam du dimanche à VOYVOY",
    description:
      "Musique live, open mic et jam à VOYVOY, Cabarete. Lester Grant lance la soirée — apportez un instrument ou empruntez-en un. Ambiance détendue pour boire et dîner.",
    date: "2026-07-05",
    time: "5:00 PM",
    location: "Cabarete",
    venue: "VOYVOY Cabarete",
    category: "music",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 0,
    imageEmoji: "🎸",
  },
  {
    id: "voyvoy-saturday-session",
    title: "Saturday Session à VOYVOY",
    description:
      "Soirée danse le samedi à VOYVOY avec DJs invités — reggaeton, club, sans cover. Un incontournable de Cabarete pour locaux et visiteurs.",
    date: "2026-07-11",
    time: "9:00 PM",
    location: "Cabarete",
    venue: "VOYVOY Cabarete",
    category: "parties",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6,
    imageEmoji: "🪩",
  },
  {
    id: "costambar-acoustic",
    title: "Acoustiques du dimanche à Costambar",
    description:
      "Les habitants et visiteurs apportent leurs guitares pour des sets informels au beach bar. Entrée libre.",
    date: "2026-07-05",
    time: "5:00 PM",
    location: "Costambar",
    venue: "Costambar Beach Club",
    category: "music",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 0,
    imageEmoji: "🎸",
  },
  {
    id: "malecon-live-concert",
    title: "Concerts en plein air sur le Malecón",
    description:
      "Concerts gratuits en bord de mer avec des artistes dominicains le long du Malecón de Puerto Plata.",
    date: "2026-07-10",
    time: "8:00 PM",
    location: "Puerto Plata",
    venue: "Malecón de Puerto Plata",
    category: "concert",
    format: "physical",
    trending: true,
    imageEmoji: "🎵",
  },
  {
    id: "rumble-in-paradise-12",
    title: "Rumble in Paradise 12",
    description:
      "Boxe professionnelle sur la plage de Sosúa au Bar 39, avec invités spéciaux et séances d'autographes.",
    date: "2026-07-04",
    time: "5:00 PM",
    location: "Sosúa",
    venue: "Bar 39, Playa Sosúa",
    category: "sports",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/events/1614506996278636",
    imageEmoji: "🥊",
  },
  {
    id: "cabarete-kite-fest",
    title: "Festival de kite surf à Cabarete",
    description:
      "Compétition internationale de kite surf et fête sur la plage avec les célèbres vents de Cabarete.",
    date: "2026-07-12",
    time: "10:00 AM",
    location: "Cabarete",
    venue: "Kite Beach",
    category: "sports",
    format: "physical",
    trending: true,
    imageEmoji: "🏄",
  },
  {
    id: "sosua-beach-volleyball",
    title: "Ligue de beach-volley à Sosúa",
    description:
      "Beach-volley hebdomadaire — locaux, expats et touristes mélangent les équipes. Il suffit de se présenter.",
    date: "2026-07-05",
    time: "4:00 PM",
    location: "Sosúa",
    venue: "Playa Sosúa",
    category: "sports",
    format: "physical",
    trending: true,
    recurrence: "weekly",
    recurrenceDay: 0,
    imageEmoji: "🏐",
  },
  {
    id: "pp-sunday-futbol",
    title: "Football du dimanche à Puerto Plata",
    description:
      "Match informel le dimanche au terrain municipal. Tous niveaux — demandez à n'importe quel colmado près du parc.",
    date: "2026-07-05",
    time: "8:00 AM",
    location: "Puerto Plata",
    venue: "Parque Central",
    category: "sports",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 0,
    imageEmoji: "⚽",
  },
  {
    id: "cabarete-surf-comp",
    title: "Course surf & SUP à Cabarete",
    description:
      "Course communautaire de surf et paddle dans la baie de Cabarete. Inscription sur la plage le jour même.",
    date: "2026-07-13",
    time: "7:00 AM",
    location: "Cabarete",
    venue: "Cabarete Bay",
    category: "sports",
    format: "physical",
    imageEmoji: "🏄",
  },
  {
    id: "womens-reconnection-kite-camp-2026",
    title: "Women's Reconnection Kite Camp",
    description:
      "Camp de kite de 7 nuits pour femmes en bord de mer à Cabarete — flow, reconnexion et sessions kite avec l'instructrice IKO Ariadna Rabasa. Places early bird disponibles.",
    date: "2026-08-01",
    endDate: "2026-08-08",
    time: "12:00 AM",
    location: "Cabarete",
    venue: "Playa Cabarete",
    category: "sports",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/events/1683911749456298/",
    imageEmoji: "🏄",
  },
  {
    id: "pp-food-truck",
    title: "Rally food trucks à Puerto Plata",
    description:
      "Chefs locaux, cocktails artisanaux et merengue live sur le Malecón. Soirée familiale.",
    date: "2026-07-08",
    time: "5:00 PM",
    location: "Puerto Plata",
    venue: "Malecón de Puerto Plata",
    category: "food-drinks",
    format: "physical",
    trending: true,
    imageEmoji: "🍔",
  },
  {
    id: "cabarete-brunch-market",
    title: "Marché brunch de Cabarete",
    description:
      "Produits frais, pain artisanal et stands brunch en bord de mer. Rituel du samedi pour la communauté.",
    date: "2026-07-04",
    time: "9:00 AM",
    location: "Cabarete",
    venue: "Cabarete Town Center",
    category: "food-drinks",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6,
    imageEmoji: "🍔",
  },
  {
    id: "circus-fest",
    title: "Festival d'été Playa Dorada",
    description:
      "Festival de trois jours avec spectacles live, stands de nourriture et activités familiales.",
    date: "2026-07-18",
    endDate: "2026-07-20",
    time: "12:00 PM",
    location: "Playa Dorada",
    venue: "Playa Dorada Complex",
    category: "festivals",
    format: "physical",
    trending: true,
    imageEmoji: "🎪",
  },
  {
    id: "pp-cultural-fair",
    title: "Foire culturelle de Puerto Plata",
    description:
      "Artisanat, musique típico et street food célébrant le patrimoine de la Côte Nord.",
    date: "2026-07-15",
    time: "11:00 AM",
    location: "Puerto Plata",
    venue: "Centro Histórico",
    category: "festivals",
    format: "physical",
    imageEmoji: "🎪",
  },
  {
    id: "merengue-night",
    title: "Nuit merengue & bachata",
    description:
      "Dansez toute la nuit avec des groupes típico live et des cours de bachata sur la piste.",
    date: "2026-07-11",
    time: "9:00 PM",
    location: "Puerto Plata",
    venue: "Centro Histórico",
    category: "dance",
    format: "physical",
    trending: true,
    imageEmoji: "💃",
  },
  {
    id: "cabarete-breathwork",
    title: "Cercle breathwork à Cabarete",
    description:
      "Séance de breathwork et sound healing en petit groupe. Places limitées — contactez l'organisateur.",
    date: "2026-07-07",
    time: "6:00 PM",
    location: "Cabarete",
    venue: "Cabarete Wellness Studio",
    category: "health-wellness",
    format: "physical",
    imageEmoji: "🧘",
  },
  {
    id: "cabarete-pilates-reformer",
    title: "Cours collectif Pilates Reformer",
    description:
      "Sessions collectives de Pilates Reformer à Cabarete avec Rafaella Cirillo. Places limitées — DM ou WhatsApp +1 809 460 5777. Code RC-pilates pour le premier cours.",
    date: "2026-07-08",
    time: "9:00 AM",
    location: "Cabarete",
    venue: "Cabarete",
    category: "health-wellness",
    format: "physical",
    recurrence: "weekly",
    recurrenceDays: [2, 4],
    sourceUrl: "https://www.facebook.com/events/981611704653706/",
    imageEmoji: "🧘",
  },
  {
    id: "pp-comedy-night",
    title: "Comédie & storytelling à Puerto Plata",
    description:
      "Soirée bilingue de stand-up et contes dans un bar local. Scène underground, beaucoup de rires.",
    date: "2026-07-12",
    time: "8:30 PM",
    location: "Puerto Plata",
    venue: "Calle de las Sombrillas",
    category: "performances",
    format: "physical",
    imageEmoji: "🎤",
  },
  {
    id: "startup-meetup",
    title: "Meetup startups Côte Nord",
    description:
      "Networking mensuel pour entrepreneurs et nomades digitaux en RD. Café et pitches.",
    date: "2026-07-10",
    time: "7:00 PM",
    location: "Cabarete",
    venue: "Cowork Cabarete",
    category: "business",
    format: "hybrid",
    imageEmoji: "💼",
  },
  {
    id: "virtual-tech-talk",
    title: "Tech Talks des Caraïbes (en ligne)",
    description:
      "Panel virtuel gratuit sur créer des produits depuis la République dominicaine. Q&A inclus.",
    date: "2026-07-09",
    time: "8:00 PM",
    location: "En ligne",
    venue: "Zoom",
    category: "business",
    format: "digital",
    imageEmoji: "💻",
  },
  {
    id: "reggaeton-party",
    title: "Pool party Côte Nord",
    description:
      "DJs, ambiance piscine et cocktails tropicaux. +21 après 22h.",
    date: "2026-07-13",
    time: "4:00 PM",
    location: "Puerto Plata",
    venue: "Ocean World",
    category: "parties",
    format: "physical",
    imageEmoji: "🪩",
  },
  {
    id: "cabarete-full-moon",
    title: "Fête pleine lune à Cabarete",
    description:
      "Rassemblement mensuel sur la plage avec danseurs du feu et DJs. Bouche-à-oreille.",
    date: "2026-07-14",
    time: "10:00 PM",
    location: "Cabarete",
    venue: "Cabarete Beach",
    category: "parties",
    format: "physical",
    trending: true,
    imageEmoji: "🪩",
  },
];
