import type { Event } from "./types";
import type { Locale } from "@/i18n/config";

const FALLBACK_EVENTS_EN: Event[] = [
  {
    id: "sosua-beach-jam",
    title: "Sosúa Beach Live Music",
    description:
      "Weekly sunset sessions with local bands and DJs on the North Coast. Free entry, drinks available.",
    date: "2026-07-05",
    time: "6:00 PM",
    location: "Sosúa",
    venue: "Playa Sosúa",
    category: "music",
    format: "physical",
    trending: true,
    imageEmoji: "🎸",
  },
  {
    id: "cabarete-kite-fest",
    title: "Cabarete Kite Festival",
    description:
      "International kite surfing competition and beach party on the world-famous Cabarete winds.",
    date: "2026-07-12",
    time: "10:00 AM",
    location: "Cabarete",
    venue: "Kite Beach",
    category: "sports",
    format: "physical",
    trending: true,
    imageEmoji: "⚽",
  },
  {
    id: "pp-food-truck",
    title: "Puerto Plata Food Truck Rally",
    description:
      "Local chefs, craft cocktails, and live merengue by the Malecón. Family-friendly evening.",
    date: "2026-07-08",
    time: "5:00 PM",
    location: "Puerto Plata",
    venue: "Malecón de Puerto Plata",
    category: "food-drinks",
    format: "physical",
    trending: true,
    imageEmoji: "🍔",
  },
  {
    id: "wellness-sunrise",
    title: "Sunrise Yoga on the Coast",
    description:
      "Guided beach yoga and meditation session. Mats provided. All levels welcome.",
    date: "2026-07-06",
    time: "6:30 AM",
    location: "Costambar",
    venue: "Costambar Beach",
    category: "health-wellness",
    format: "physical",
    imageEmoji: "🧘",
  },
  {
    id: "merengue-night",
    title: "Merengue & Bachata Night",
    description:
      "Dance the night away with live típico bands and open-floor bachata lessons.",
    date: "2026-07-11",
    time: "9:00 PM",
    location: "Puerto Plata",
    venue: "Centro Histórico",
    category: "dance",
    format: "physical",
    trending: true,
    imageEmoji: "💃",
  },
  {
    id: "startup-meetup",
    title: "North Coast Startup Meetup",
    description:
      "Monthly networking for entrepreneurs and remote workers in the DR. Coffee and pitches.",
    date: "2026-07-10",
    time: "7:00 PM",
    location: "Cabarete",
    venue: "Cowork Cabarete",
    category: "business",
    format: "hybrid",
    imageEmoji: "💼",
  },
  {
    id: "virtual-tech-talk",
    title: "Caribbean Tech Talks (Online)",
    description:
      "Free virtual panel on building products from the Dominican Republic. Q&A included.",
    date: "2026-07-09",
    time: "8:00 PM",
    location: "Online",
    venue: "Zoom",
    category: "business",
    format: "digital",
    imageEmoji: "💻",
  },
  {
    id: "circus-fest",
    title: "Playa Dorada Summer Fest",
    description:
      "Three-day festival with live acts, food stalls, and family activities by the resort zone.",
    date: "2026-07-18",
    endDate: "2026-07-20",
    time: "12:00 PM",
    location: "Playa Dorada",
    venue: "Playa Dorada Complex",
    category: "festivals",
    format: "physical",
    trending: true,
    imageEmoji: "🎪",
  },
  {
    id: "open-mic",
    title: "Coastal Open Mic Night",
    description:
      "Singers, poets, and comedians take the stage. Sign up at the door.",
    date: "2026-07-07",
    time: "8:00 PM",
    location: "Sosúa",
    venue: "El Batey",
    category: "performances",
    format: "physical",
    imageEmoji: "🎤",
  },
  {
    id: "reggaeton-party",
    title: "North Coast Pool Party",
    description:
      "DJ sets, pool vibes, and tropical cocktails. 21+ after 10 PM.",
    date: "2026-07-13",
    time: "4:00 PM",
    location: "Puerto Plata",
    venue: "Ocean World",
    category: "parties",
    format: "physical",
    imageEmoji: "🪩",
  },
];

const FALLBACK_EVENTS_ES: Event[] = [
  {
    id: "sosua-beach-jam",
    title: "Música en Vivo en la Playa de Sosúa",
    description:
      "Sesiones semanales al atardecer con bandas locales y DJs en la Costa Norte. Entrada gratis, bebidas disponibles.",
    date: "2026-07-05",
    time: "6:00 PM",
    location: "Sosúa",
    venue: "Playa Sosúa",
    category: "music",
    format: "physical",
    trending: true,
    imageEmoji: "🎸",
  },
  {
    id: "cabarete-kite-fest",
    title: "Festival de Kite Surf en Cabarete",
    description:
      "Competencia internacional de kite surf y fiesta en la playa con los famosos vientos de Cabarete.",
    date: "2026-07-12",
    time: "10:00 AM",
    location: "Cabarete",
    venue: "Kite Beach",
    category: "sports",
    format: "physical",
    trending: true,
    imageEmoji: "⚽",
  },
  {
    id: "pp-food-truck",
    title: "Rally de Food Trucks en Puerto Plata",
    description:
      "Chefs locales, cócteles artesanales y merengue en vivo en el Malecón. Ambiente familiar.",
    date: "2026-07-08",
    time: "5:00 PM",
    location: "Puerto Plata",
    venue: "Malecón de Puerto Plata",
    category: "food-drinks",
    format: "physical",
    trending: true,
    imageEmoji: "🍔",
  },
  {
    id: "wellness-sunrise",
    title: "Yoga al Amanecer en la Costa",
    description:
      "Sesión guiada de yoga y meditación en la playa. Tapetes incluidos. Todos los niveles.",
    date: "2026-07-06",
    time: "6:30 AM",
    location: "Costambar",
    venue: "Playa Costambar",
    category: "health-wellness",
    format: "physical",
    imageEmoji: "🧘",
  },
  {
    id: "merengue-night",
    title: "Noche de Merengue y Bachata",
    description:
      "Baila toda la noche con bandas de típico en vivo y clases de bachata en la pista.",
    date: "2026-07-11",
    time: "9:00 PM",
    location: "Puerto Plata",
    venue: "Centro Histórico",
    category: "dance",
    format: "physical",
    trending: true,
    imageEmoji: "💃",
  },
  {
    id: "startup-meetup",
    title: "Meetup de Startups Costa Norte",
    description:
      "Networking mensual para emprendedores y nómadas digitales en RD. Café y pitches.",
    date: "2026-07-10",
    time: "7:00 PM",
    location: "Cabarete",
    venue: "Cowork Cabarete",
    category: "business",
    format: "hybrid",
    imageEmoji: "💼",
  },
  {
    id: "virtual-tech-talk",
    title: "Charlas Tech del Caribe (En línea)",
    description:
      "Panel virtual gratuito sobre crear productos desde República Dominicana. Incluye Q&A.",
    date: "2026-07-09",
    time: "8:00 PM",
    location: "En línea",
    venue: "Zoom",
    category: "business",
    format: "digital",
    imageEmoji: "💻",
  },
  {
    id: "circus-fest",
    title: "Festival de Verano Playa Dorada",
    description:
      "Festival de tres días con actos en vivo, puestos de comida y actividades familiares.",
    date: "2026-07-18",
    endDate: "2026-07-20",
    time: "12:00 PM",
    location: "Playa Dorada",
    venue: "Complejo Playa Dorada",
    category: "festivals",
    format: "physical",
    trending: true,
    imageEmoji: "🎪",
  },
  {
    id: "open-mic",
    title: "Noche de Micrófono Abierto",
    description:
      "Cantantes, poetas y comediantes en el escenario. Inscríbete en la puerta.",
    date: "2026-07-07",
    time: "8:00 PM",
    location: "Sosúa",
    venue: "El Batey",
    category: "performances",
    format: "physical",
    imageEmoji: "🎤",
  },
  {
    id: "reggaeton-party",
    title: "Fiesta en la Piscina Costa Norte",
    description:
      "DJs, ambiente de piscina y cócteles tropicales. +21 después de las 10 PM.",
    date: "2026-07-13",
    time: "4:00 PM",
    location: "Puerto Plata",
    venue: "Ocean World",
    category: "parties",
    format: "physical",
    imageEmoji: "🪩",
  },
];

export function getFallbackEvents(locale: Locale = "es"): Event[] {
  return locale === "en" ? FALLBACK_EVENTS_EN : FALLBACK_EVENTS_ES;
}
