import type { Event } from "./types";
import { ATLETICOS_HOME_GAMES_FR } from "./atleticos-summer-league-2026";

/** French translations of curated North Coast events. */
export const FALLBACK_EVENTS_FR: Event[] = [
  {
    id: "voyvoy-sunday-open-mic",
    title: "Open mic & jam du dimanche à VOYVOY",
    description:
      "Musique live, open mic et jam à VOYVOY, Cabarete. Lester Grant lance la soirée — apportez un instrument ou empruntez-en un. Ambiance détendue pour boire et dîner.",
    date: "2026-07-05",
    time: "5:00 PM – 11:00 PM",
    location: "Cabarete",
    venue: "VOYVOY Cabarete",
    venueSlug: "voyvoy-cabarete",
    category: "performances",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 0,
    imageEmoji: "🎤",
  },
  {
    id: "voyvoy-saturday-session",
    title: "Saturday Session à VOYVOY",
    description:
      "Soirée danse le samedi à VOYVOY avec DJs invités — reggaeton, club, sans cover. Un incontournable de Cabarete pour locaux et visiteurs.",
    date: "2026-07-11",
    time: "9:00 PM – 2:00 AM",
    location: "Cabarete",
    venue: "VOYVOY Cabarete",
    venueSlug: "voyvoy-cabarete",
    category: "parties",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6,
    imageEmoji: "🪩",
  },
  {
    id: "malecon-live-concert",
    title: "Concerts en plein air sur le Malecón",
    description:
      "Soirées de week-end sur le Malecón de Puerto Plata : sets informels sur la promenade et concerts occasionnels à l'Anfiteatro La Puntilla. Les programmations sont annoncées par date — consultez la page officielle du lieu lorsqu'un événement est prévu.",
    date: "2026-01-01",
    time: "7:00 PM – 10:00 PM",
    location: "Puerto Plata",
    venue: "Anfiteatro La Puntilla",
    venueSlug: "malecon-puerto-plata",
    address: "Desvío a La Puntilla",
    category: "music",
    format: "physical",
    recurrence: "weekends",
    sourceUrl: "https://es.godominicanrepublic.com/que-hacer/anfiteatro-la-puntilla",
    imageEmoji: "🎵",
  },
  {
    id: "rumble-in-paradise-12",
    title: "Rumble in Paradise 12",
    description:
      "Boxe professionnelle sur la plage de Sosúa au Bar 39, avec invités spéciaux et séances d'autographes.",
    date: "2026-07-04",
    time: "5:00 PM – 9:00 PM",
    location: "Sosúa",
    venue: "Bar 39, Playa Sosúa",
    venueSlug: "bar-39-sosua",
    category: "sports",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/events/1614506996278636",
    imageEmoji: "🥊",
  },
  ...ATLETICOS_HOME_GAMES_FR,
  {
    id: "cabarete-classic-2026",
    title: "Cabarete Classic 2026",
    description:
      "Quatre jours de windsurf, kitesurf, wingfoil et foil sur la plage de Cabarete (16–19 juil.). La grande régate des sports de vent des Caraïbes — compétiteurs internationaux, cliniques et musique le soir sur la plage.",
    date: "2026-07-16",
    endDate: "2026-07-19",
    time: "12:00 AM",
    location: "Cabarete",
    venue: "Playa Cabarete",
    venueSlug: "kite-beach",
    address: "Residencial Mañanero, 57600 Sosúa, República Dominicana",
    category: "sports",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/events/4550504901861035/",
    imageEmoji: "🏄",
  },
  {
    id: "womens-reconnection-kite-camp-2026",
    title: "Women's Reconnection Kite Camp",
    description:
      "Camp de kite de 7 nuits pour femmes en bord de mer à Cabarete — flow, reconnexion et sessions kite avec l'instructrice IKO Ariadna Rabasa. Places early bird disponibles.",
    date: "2026-08-01",
    endDate: "2026-08-08",
    time: "12:00 AM",
    location: "Cabarete",
    venue: "Playa Cabarete",
    venueSlug: "kite-beach",
    category: "sports",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/events/1683911749456298/",
    imageEmoji: "🏄",
  },
  {
    id: "cabarete-pilates-reformer",
    title: "Cours collectif Pilates Reformer",
    description:
      "Cours collectifs de Pilates Reformer à Cabarete avec Rafaella Cirillo (mar. et jeu. 9 h). L'adresse du studio est communiquée à la réservation — DM ou WhatsApp +1 809 460 5777. Code RC-pilates pour le premier cours.",
    date: "2026-07-08",
    time: "9:00 AM – 10:00 AM",
    location: "Cabarete",
    venue: "Rafaella's Studio",
    category: "health-wellness",
    format: "physical",
    recurrence: "weekly",
    recurrenceDays: [2, 4],
    sourceUrl: "https://www.facebook.com/events/981611704653706/",
    imageEmoji: "🧘",
  },
  {
    id: "feria-artesanal-verano-2026",
    title: "Feria Artesanal Verano 2026",
    description:
      "La foire artisanale d'été 2026 se tient du 10 au 26 juillet sur la Plaza Independencia (le parc central de Puerto Plata). Plus de 120 artisans locaux y exposent tous les jours de 8 h à 21 h : pièces faites main, expositions culturelles, art, souvenirs et masques de cabezudos. L'initiative vise à mettre en valeur les artistes locaux et rapprocher l'artisanat dominicain des visiteurs et des résidents.",
    date: "2026-07-10",
    endDate: "2026-07-26",
    time: "8:00 AM – 9:00 PM",
    location: "Puerto Plata",
    venue: "Plaza Independencia (Parque Central)",
    venueSlug: "plaza-independencia",
    address: "Calle San Felipe, Puerto Plata",
    category: "festivals",
    categories: ["culture"],
    format: "physical",
    trending: true,
    sourceUrl: "https://www.facebook.com/share/18vHNaoe69/",
    imageEmoji: "🎨",
  },
  {
    id: "puerto-plata-carnaval-2026",
    title: "Carnaval Puerto Plata 2026",
    description:
      "Carnaval Puerto Plata 2026 sur le Malecón — parades dominicales chaque dimanche de février (1, 8, 15 et 22 fév.) culminant avec le Gran Desfile Final le 1er mars à l'Anfiteatro La Puntilla. Masques taimáscaro, comparsas et culture folklorique dominicaine.",
    date: "2026-02-01",
    endDate: "2026-03-01",
    time: "2:00 PM – 8:00 PM",
    location: "Puerto Plata",
    venue: "Malecón de Puerto Plata et Anfiteatro La Puntilla",
    venueSlug: "malecon-puerto-plata",
    category: "festivals",
    format: "physical",
    trending: true,
    sourceUrl:
      "https://sea-horse-ranch.com/carnival-celebrations-in-the-dominican-republic/",
    imageEmoji: "🎭",
  },
  {
    id: "malecon-morning-wellness-walk",
    title: "Marche wellness matinale sur le Malecón",
    description:
      "Marcheurs et joggeurs tôt le matin sur le Malecón de Puerto Plata — brise marine, groupes d'étirement et rituel de bienêtre quotidien sur la promenade.",
    date: "2026-01-01",
    time: "6:00 AM – 8:00 AM",
    location: "Puerto Plata",
    venue: "Malecón de Puerto Plata",
    venueSlug: "malecon-puerto-plata",
    category: "health-wellness",
    format: "physical",
    recurrence: "daily",
    imageEmoji: "🚶",
  },
  {
    id: "ingest-18th-annual-cabarete-butterfly-effect",
    title: "18e Cabarete Butterfly Effect",
    description:
      "Festival femmes et sports nautiques sur cinq jours à Cabarete (7–11 juil.) : SUP, yoga, nettoyage de plage, croisière catamaran et paddle sur la rivière. Programme et inscription sur le site officiel.",
    date: "2026-07-07",
    endDate: "2026-07-11",
    time: "9:00 AM – 9:00 PM",
    location: "Cabarete",
    venue: "Kite Beach et Cabarete",
    address: "Carretera 5",
    venueSlug: "kite-beach",
    category: "festivals",
    format: "physical",
    trending: true,
    sourceUrl: "https://www.cabaretebutterflyeffect.com/",
    imageEmoji: "🏄",
  },
  {
    id: "sancocho-sabados-pingui",
    title: "Sancocho du samedi chez Pingüi",
    description:
      "Le samedi goûte la tradition chez Pingüi Bar — dégustez un sancocho face à la mer à Playa El Pueblito. Réunissez amis et famille pour un après-midi de cuisine dominicaine avec vue sur l'océan (12 h–16 h).",
    date: "2026-07-11",
    time: "12:00 PM – 4:00 PM",
    location: "Puerto Plata",
    venue: "Pingüi Bar Restaurant & Piña Colada House",
    address: "C. B, Puerto Plata 57000",
    lat: 19.773903,
    lng: -70.652704,
    category: "food-drinks",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6,
    sourceUrl:
      "https://www.facebook.com/events/1547520700301499/1547522116968024/",
    imageEmoji: "🍲",
  },
  {
    id: "el-colibri-karaoke-battle-2026",
    title: "Karaoke Battle El Colibri — Jeudis",
    description:
      "Soirées karaoké le jeudi à l'El Colibri Hotel, Sosúa (19 h–minuit). Participez au Karaoke Battle sur 8 semaines — 20 000 $ de prix (2 juil.–3 sept. 2026). Les candidats doivent être présents chaque jeudi pour rester éligibles. Inscription par WhatsApp : +1 917-523-7259.",
    date: "2026-07-02",
    endDate: "2026-09-03",
    time: "7:00 PM – 12:00 AM",
    location: "Sosúa",
    venue: "El Colibri Hotel",
    venueSlug: "el-colibri-hotel",
    address: "141 Pedro Clisante, Sosúa 57600",
    lat: 19.7545,
    lng: -70.519,
    category: "music",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 4,
    trending: true,
    sourceUrl: "https://www.elcolibriresort.com/",
    imageEmoji: "🎤",
  },
  {
    id: "inicio-del-campamento-pp-2026",
    title: "Ouverture du camp sportif",
    description:
      "Lancement d'un camp sportif dans le quartier historique de San Felipe, Puerto Plata — organisé par Sin pelos en la lengua. Consultez l'événement Facebook pour l'inscription.",
    date: "2026-07-10",
    time: "5:00 PM – 8:00 PM",
    location: "Puerto Plata",
    venue: "San Felipe de Puerto Plata",
    venueSlug: "fortaleza-san-felipe",
    category: "sports",
    format: "physical",
    sourceUrl: "https://www.facebook.com/events/1017381540870816/",
    imageEmoji: "⚽",
  },
];
