import type { Event } from "./types";
import type { Locale } from "@/i18n/config";

/** Evergreen North Coast happenings — show up on Today / Weekend filters every week */
const RECURRING_EN: Event[] = [
  {
    id: "lax-sunset-daily",
    title: "LAX Sunset Sessions",
    description:
      "Nightly DJs and live bands on the beach deck. The default Cabarete evening — no cover most nights.",
    date: "2026-01-01",
    time: "6:00 PM",
    location: "Cabarete",
    venue: "LAX Cabarete",
    venueSlug: "lax-cabarete",
    category: "music",
    format: "physical",
    trending: true,
    recurrence: "daily",
    imageEmoji: "🎸",
  },
  {
    id: "malecon-kiosks-daily",
    title: "Malecón Evening Food Kiosks",
    description:
      "Street food, cold Presidentes, and típico drifting from the waterfront stalls every evening.",
    date: "2026-01-01",
    time: "5:00 PM",
    location: "Puerto Plata",
    venue: "Malecón de Puerto Plata",
    venueSlug: "malecon-puerto-plata",
    category: "food-drinks",
    format: "physical",
    recurrence: "daily",
    imageEmoji: "🍔",
  },
  {
    id: "kite-beach-daily",
    title: "Kite Beach Wind Session",
    description:
      "Morning kite and wing lessons, races, and beach hangouts when the trade winds kick in — most days here.",
    date: "2026-01-01",
    time: "10:00 AM",
    location: "Cabarete",
    venue: "Kite Beach",
    venueSlug: "kite-beach",
    category: "sports",
    format: "physical",
    trending: true,
    recurrence: "daily",
    imageEmoji: "🏄",
  },
  {
    id: "cabarete-yoga-daily",
    title: "Cabarete Sunrise Beach Yoga",
    description:
      "Drop-in beach yoga most mornings. Mats on the sand, all levels — pay what you can or BYO mat.",
    date: "2026-01-01",
    time: "7:00 AM",
    location: "Cabarete",
    venue: "Cabarete Beach",
    category: "health-wellness",
    format: "physical",
    recurrence: "daily",
    imageEmoji: "🧘",
  },
  {
    id: "cowork-weekdays",
    title: "Cowork Cabarete Open Desk & Coffee",
    description:
      "Remote workers and founders coworking weekdays — informal networking at the bar after 4 PM.",
    date: "2026-01-01",
    time: "9:00 AM",
    location: "Cabarete",
    venue: "Cowork Cabarete",
    venueSlug: "cowork-cabarete",
    category: "business",
    format: "physical",
    recurrence: "weekdays",
    imageEmoji: "💼",
  },
  {
    id: "batey-salsa-weekly",
    title: "El Batey Salsa Social",
    description:
      "Weekly salsa night — beginner class then social dancing until late. No partner needed.",
    date: "2026-01-01",
    time: "8:00 PM",
    location: "Sosúa",
    venue: "El Batey",
    venueSlug: "el-batey-sosua",
    category: "dance",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 3, // Wednesday
    imageEmoji: "💃",
  },
  {
    id: "sosua-volleyball-weekly",
    title: "Sosúa Beach Volleyball Pickup",
    description:
      "Locals and visitors mix teams on the sand every week. Just show up and jump in.",
    date: "2026-01-01",
    time: "4:00 PM",
    location: "Sosúa",
    venue: "Playa Sosúa",
    category: "sports",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 4, // Thursday
    imageEmoji: "🏐",
  },
  {
    id: "lax-reggae-friday",
    title: "LAX Friday Reggae Night",
    description:
      "Reggae and roots every Friday on the bay — one of Cabarete's longest-running weekly parties.",
    date: "2026-01-01",
    time: "9:00 PM",
    location: "Cabarete",
    venue: "LAX Cabarete",
    venueSlug: "lax-cabarete",
    category: "parties",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 5, // Friday
    trending: true,
    imageEmoji: "🪩",
  },
  {
    id: "batey-open-mic-weekly",
    title: "El Batey Open Mic",
    description:
      "Singers, poets, and comedians sign up at the door. Underground scene, bilingual crowd.",
    date: "2026-01-01",
    time: "8:00 PM",
    location: "Sosúa",
    venue: "El Batey",
    venueSlug: "el-batey-sosua",
    category: "performances",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 2, // Tuesday
    imageEmoji: "🎤",
  },
  {
    id: "sea-horse-saturday-market",
    title: "Sea Horse Ranch Saturday Market",
    description:
      "Shop local every Saturday with local artisans, fresh food, organic produce, and boutique fashions on the Sea Horse Ranch Tennis Club lawn.",
    date: "2026-01-01",
    time: "10:00 AM - 1:00 PM",
    location: "Cabarete-Sosúa",
    venue: "Sea Horse Ranch Tennis Club Lawn",
    venueSlug: "sea-horse-ranch",
    category: "food-drinks",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6, // Saturday
    sourceUrl: "https://www.sea-horse-ranch.com",
    imageEmoji: "🧺",
  },
  {
    id: "ocean-world-daily",
    title: "Ocean World Adventure Park",
    description:
      "Marine park open daily in Cofresí — dolphin encounters, sea lion and shark shows, exotic birds, reef snorkeling, and a giant water slide. Plan 4–6 hours.",
    date: "2026-01-01",
    time: "9:00 AM - 6:00 PM",
    location: "Puerto Plata",
    address: "Cofresí, Puerto Plata",
    venue: "Ocean World Adventure Park",
    venueSlug: "ocean-world",
    category: "festivals",
    format: "physical",
    recurrence: "daily",
    sourceUrl:
      "https://es.godominicanrepublic.com/que-hacer/ocean-world-adventure-park",
    imageEmoji: "🐬",
  },
  {
    id: "charcos-damajagua-daily",
    title: "27 Charcos de Damajagua — Park Hours",
    description:
      "Guided waterfall treks through limestone pools — most tours cover seven cascades; full 27-charco route for fit adventurers. ~1 hour from Puerto Plata.",
    date: "2026-01-01",
    time: "8:30 AM - 4:00 PM",
    location: "Puerto Plata",
    venue: "27 Charcos de Damajagua",
    venueSlug: "charcos-damajagua",
    category: "sports",
    format: "physical",
    recurrence: "daily",
    sourceUrl:
      "https://es.godominicanrepublic.com/que-hacer/27-charcos-de-damajagua",
    imageEmoji: "💧",
  },
  {
    id: "fortaleza-san-felipe-daily",
    title: "Fortaleza San Felipe — Museum Hours",
    description:
      "16th-century Spanish fortress and museum — original cannons, colonial weapons, and Atlantic views. Sunset from La Puntilla park nearby.",
    date: "2026-01-01",
    time: "10:00 AM - 6:00 PM",
    location: "Puerto Plata",
    address: "Av. Gral. Gregorio Luperón",
    venue: "Fortaleza San Felipe",
    venueSlug: "fortaleza-san-felipe",
    category: "festivals",
    format: "physical",
    recurrence: "daily",
    sourceUrl:
      "https://es.godominicanrepublic.com/que-hacer/fortaleza-san-felipe",
    imageEmoji: "🏰",
  },
  {
    id: "museo-ambar-weekdays",
    title: "Museo del Ámbar — Museum Hours",
    description:
      "Victorian mansion in the historic center — Dominican amber fossils including lizards, scorpions, and insects millions of years old.",
    date: "2026-01-01",
    time: "9:00 AM - 5:00 PM",
    location: "Puerto Plata",
    address: "Calle Duarte 61",
    venue: "Museo del Ámbar",
    venueSlug: "museo-ambar",
    category: "festivals",
    format: "physical",
    recurrence: "weekdays",
    sourceUrl: "https://es.godominicanrepublic.com/que-hacer/museo-del-ambar",
    imageEmoji: "🟠",
  },
  {
    id: "museo-ambar-saturday",
    title: "Museo del Ámbar — Saturday Hours",
    description:
      "Shorter Saturday hours at the amber museum in downtown Puerto Plata. Closed Sundays.",
    date: "2026-01-01",
    time: "9:00 AM - 3:00 PM",
    location: "Puerto Plata",
    address: "Calle Duarte 61",
    venue: "Museo del Ámbar",
    venueSlug: "museo-ambar",
    category: "festivals",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6,
    sourceUrl: "https://es.godominicanrepublic.com/que-hacer/museo-del-ambar",
    imageEmoji: "🟠",
  },
  {
    id: "teleferico-puerto-plata-daily",
    title: "Teleférico Puerto Plata — Cable Car",
    description:
      "Caribbean cable car to Pico Isabel de Torres — Christ statue and botanical gardens. Check if operating; renovation has closed the lift at times — safari truck tours may run instead.",
    date: "2026-01-01",
    time: "8:30 AM - 5:00 PM",
    location: "Puerto Plata",
    address: "C. del Teleférico",
    venue: "Teleférico Puerto Plata",
    venueSlug: "teleferico-puerto-plata",
    category: "sports",
    format: "physical",
    recurrence: "daily",
    sourceUrl: "https://es.godominicanrepublic.com/destinos/puerto-plata",
    imageEmoji: "🚡",
  },
  {
    id: "cayo-arena-tours-daily",
    title: "Cayo Arena — Boat Tours",
    description:
      "Sandbar island (Cayo Paraíso) reached by boat from Punta Rucia — ~25 minutes each way. Shallow turquoise water, white sand, and snorkeling. Most operators run morning trips.",
    date: "2026-01-01",
    time: "8:00 AM - 12:00 PM",
    location: "Puerto Plata",
    venue: "Cayo Arena",
    venueSlug: "cayo-arena",
    category: "sports",
    format: "physical",
    recurrence: "daily",
    sourceUrl: "https://es.godominicanrepublic.com/que-hacer/cayo-arena",
    imageEmoji: "🏝️",
  },
];

const RECURRING_ES: Event[] = [
  {
    id: "lax-sunset-daily",
    title: "Sesiones al atardecer en LAX",
    description:
      "DJs y bandas en vivo cada noche en la terraza de la playa. La noche clásica de Cabarete.",
    date: "2026-01-01",
    time: "6:00 PM",
    location: "Cabarete",
    venue: "LAX Cabarete",
    venueSlug: "lax-cabarete",
    category: "music",
    format: "physical",
    trending: true,
    recurrence: "daily",
    imageEmoji: "🎸",
  },
  {
    id: "malecon-kiosks-daily",
    title: "Kioscos nocturnos del Malecón",
    description:
      "Comida callejera, frío y música típica en el paseo marítimo cada tarde-noche.",
    date: "2026-01-01",
    time: "5:00 PM",
    location: "Puerto Plata",
    venue: "Malecón de Puerto Plata",
    venueSlug: "malecon-puerto-plata",
    category: "food-drinks",
    format: "physical",
    recurrence: "daily",
    imageEmoji: "🍔",
  },
  {
    id: "kite-beach-daily",
    title: "Sesión de viento en Kite Beach",
    description:
      "Clases de kite, carreras y hangout en la playa cuando soplan los alisios — casi todos los días.",
    date: "2026-01-01",
    time: "10:00 AM",
    location: "Cabarete",
    venue: "Kite Beach",
    venueSlug: "kite-beach",
    category: "sports",
    format: "physical",
    trending: true,
    recurrence: "daily",
    imageEmoji: "🏄",
  },
  {
    id: "cabarete-yoga-daily",
    title: "Yoga al amanecer en Cabarete",
    description:
      "Yoga en la playa la mayoría de las mañanas. Todos los niveles — trae tu mat.",
    date: "2026-01-01",
    time: "7:00 AM",
    location: "Cabarete",
    venue: "Playa Cabarete",
    category: "health-wellness",
    format: "physical",
    recurrence: "daily",
    imageEmoji: "🧘",
  },
  {
    id: "cowork-weekdays",
    title: "Cowork Cabarete — escritorio abierto",
    description:
      "Nómadas digitales y emprendedores entre semana — networking informal en la barra después de las 4 PM.",
    date: "2026-01-01",
    time: "9:00 AM",
    location: "Cabarete",
    venue: "Cowork Cabarete",
    venueSlug: "cowork-cabarete",
    category: "business",
    format: "physical",
    recurrence: "weekdays",
    imageEmoji: "💼",
  },
  {
    id: "batey-salsa-weekly",
    title: "Social de salsa en El Batey",
    description:
      "Noche de salsa semanal — clase para principiantes y baile social hasta tarde.",
    date: "2026-01-01",
    time: "8:00 PM",
    location: "Sosúa",
    venue: "El Batey",
    venueSlug: "el-batey-sosua",
    category: "dance",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 3,
    imageEmoji: "💃",
  },
  {
    id: "sosua-volleyball-weekly",
    title: "Voleibol de playa en Sosúa",
    description:
      "Partidos informales cada semana en la arena. Solo llega y juega.",
    date: "2026-01-01",
    time: "4:00 PM",
    location: "Sosúa",
    venue: "Playa Sosúa",
    category: "sports",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 4,
    imageEmoji: "🏐",
  },
  {
    id: "lax-reggae-friday",
    title: "Noche de reggae en LAX (viernes)",
    description:
      "Reggae y roots cada viernes en la bahía — una de las fiestas semanales más clásicas.",
    date: "2026-01-01",
    time: "9:00 PM",
    location: "Cabarete",
    venue: "LAX Cabarete",
    venueSlug: "lax-cabarete",
    category: "parties",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 5,
    trending: true,
    imageEmoji: "🪩",
  },
  {
    id: "batey-open-mic-weekly",
    title: "Open mic en El Batey",
    description:
      "Cantantes, poetas y comediantes. Escena underground, público bilingüe.",
    date: "2026-01-01",
    time: "8:00 PM",
    location: "Sosúa",
    venue: "El Batey",
    venueSlug: "el-batey-sosua",
    category: "performances",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 2,
    imageEmoji: "🎤",
  },
  {
    id: "sea-horse-saturday-market",
    title: "Mercado de sábado en Sea Horse Ranch",
    description:
      "Compra local cada sábado con artesanos locales, comida fresca, productos orgánicos y moda boutique en el césped del Tennis Club de Sea Horse Ranch.",
    date: "2026-01-01",
    time: "10:00 AM - 1:00 PM",
    location: "Cabarete-Sosúa",
    venue: "Sea Horse Ranch Tennis Club Lawn",
    venueSlug: "sea-horse-ranch",
    category: "food-drinks",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6,
    sourceUrl: "https://www.sea-horse-ranch.com",
    imageEmoji: "🧺",
  },
  {
    id: "ocean-world-daily",
    title: "Ocean World Adventure Park",
    description:
      "Parque marino abierto todos los días en Cofresí — encuentros con delfines, shows de leones marinos y tiburones, aves exóticas, snorkel y tobogán acuático. Planifica 4–6 horas.",
    date: "2026-01-01",
    time: "9:00 AM - 6:00 PM",
    location: "Puerto Plata",
    address: "Cofresí, Puerto Plata",
    venue: "Ocean World Adventure Park",
    venueSlug: "ocean-world",
    category: "festivals",
    format: "physical",
    recurrence: "daily",
    sourceUrl:
      "https://es.godominicanrepublic.com/que-hacer/ocean-world-adventure-park",
    imageEmoji: "🐬",
  },
  {
    id: "charcos-damajagua-daily",
    title: "27 Charcos de Damajagua — Horario",
    description:
      "Caminatas guiadas por cascadas y pozas de piedra caliza — la mayoría de tours cubren siete charcos; la ruta completa de 27 para aventureros en buena forma. ~1 hora de Puerto Plata.",
    date: "2026-01-01",
    time: "8:30 AM - 4:00 PM",
    location: "Puerto Plata",
    venue: "27 Charcos de Damajagua",
    venueSlug: "charcos-damajagua",
    category: "sports",
    format: "physical",
    recurrence: "daily",
    sourceUrl:
      "https://es.godominicanrepublic.com/que-hacer/27-charcos-de-damajagua",
    imageEmoji: "💧",
  },
  {
    id: "fortaleza-san-felipe-daily",
    title: "Fortaleza San Felipe — Horario del museo",
    description:
      "Fortaleza española del siglo XVI y museo — cañones originales, armas coloniales y vistas al Atlántico. Atardecer desde el parque La Puntilla.",
    date: "2026-01-01",
    time: "10:00 AM - 6:00 PM",
    location: "Puerto Plata",
    address: "Av. Gral. Gregorio Luperón",
    venue: "Fortaleza San Felipe",
    venueSlug: "fortaleza-san-felipe",
    category: "festivals",
    format: "physical",
    recurrence: "daily",
    sourceUrl:
      "https://es.godominicanrepublic.com/que-hacer/fortaleza-san-felipe",
    imageEmoji: "🏰",
  },
  {
    id: "museo-ambar-weekdays",
    title: "Museo del Ámbar — Horario entre semana",
    description:
      "Mansión victoriana en el centro histórico — fósiles de ámbar dominicano con lagartos, escorpiones e insectos de millones de años.",
    date: "2026-01-01",
    time: "9:00 AM - 5:00 PM",
    location: "Puerto Plata",
    address: "Calle Duarte 61",
    venue: "Museo del Ámbar",
    venueSlug: "museo-ambar",
    category: "festivals",
    format: "physical",
    recurrence: "weekdays",
    sourceUrl: "https://es.godominicanrepublic.com/que-hacer/museo-del-ambar",
    imageEmoji: "🟠",
  },
  {
    id: "museo-ambar-saturday",
    title: "Museo del Ámbar — Horario de sábado",
    description:
      "Horario reducido los sábados en el museo del ámbar del centro de Puerto Plata. Cerrado los domingos.",
    date: "2026-01-01",
    time: "9:00 AM - 3:00 PM",
    location: "Puerto Plata",
    address: "Calle Duarte 61",
    venue: "Museo del Ámbar",
    venueSlug: "museo-ambar",
    category: "festivals",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6,
    sourceUrl: "https://es.godominicanrepublic.com/que-hacer/museo-del-ambar",
    imageEmoji: "🟠",
  },
  {
    id: "teleferico-puerto-plata-daily",
    title: "Teleférico Puerto Plata",
    description:
      "Único teleférico del Caribe al pico Isabel de Torres — estatua del Cristo y jardín botánico. Verifica si está operando; renovaciones han cerrado el teleférico a veces — pueden ofrecer tours en camión safari.",
    date: "2026-01-01",
    time: "8:30 AM - 5:00 PM",
    location: "Puerto Plata",
    address: "C. del Teleférico",
    venue: "Teleférico Puerto Plata",
    venueSlug: "teleferico-puerto-plata",
    category: "sports",
    format: "physical",
    recurrence: "daily",
    sourceUrl: "https://es.godominicanrepublic.com/destinos/puerto-plata",
    imageEmoji: "🚡",
  },
  {
    id: "cayo-arena-tours-daily",
    title: "Cayo Arena — Tours en lancha",
    description:
      "Banco de arena (Cayo Paraíso) en lancha desde Punta Rucia — ~25 minutos cada trayecto. Agua turquesa poco profunda, arena blanca y snorkel. La mayoría de operadores salen por la mañana.",
    date: "2026-01-01",
    time: "8:00 AM - 12:00 PM",
    location: "Puerto Plata",
    venue: "Cayo Arena",
    venueSlug: "cayo-arena",
    category: "sports",
    format: "physical",
    recurrence: "daily",
    sourceUrl: "https://es.godominicanrepublic.com/que-hacer/cayo-arena",
    imageEmoji: "🏝️",
  },
];

const RECURRING_FR: Event[] = [
  {
    id: "lax-sunset-daily",
    title: "Sessions sunset au LAX",
    description:
      "DJs et groupes live chaque soir sur la terrasse. La soirée classique de Cabarete.",
    date: "2026-01-01",
    time: "6:00 PM",
    location: "Cabarete",
    venue: "LAX Cabarete",
    venueSlug: "lax-cabarete",
    category: "music",
    format: "physical",
    trending: true,
    recurrence: "daily",
    imageEmoji: "🎸",
  },
  {
    id: "malecon-kiosks-daily",
    title: "Kiosques du Malecón le soir",
    description:
      "Street food, bière fraîche et musique typique sur la promenade chaque soir.",
    date: "2026-01-01",
    time: "5:00 PM",
    location: "Puerto Plata",
    venue: "Malecón de Puerto Plata",
    venueSlug: "malecon-puerto-plata",
    category: "food-drinks",
    format: "physical",
    recurrence: "daily",
    imageEmoji: "🍔",
  },
  {
    id: "kite-beach-daily",
    title: "Session kite à Kite Beach",
    description:
      "Cours, courses et hangout quand les alizés soufflent — presque tous les jours.",
    date: "2026-01-01",
    time: "10:00 AM",
    location: "Cabarete",
    venue: "Kite Beach",
    venueSlug: "kite-beach",
    category: "sports",
    format: "physical",
    trending: true,
    recurrence: "daily",
    imageEmoji: "🏄",
  },
  {
    id: "cabarete-yoga-daily",
    title: "Yoga au lever du soleil à Cabarete",
    description:
      "Yoga sur la plage la plupart des matins. Tous niveaux — apportez votre tapis.",
    date: "2026-01-01",
    time: "7:00 AM",
    location: "Cabarete",
    venue: "Plage Cabarete",
    category: "health-wellness",
    format: "physical",
    recurrence: "daily",
    imageEmoji: "🧘",
  },
  {
    id: "cowork-weekdays",
    title: "Cowork Cabarete — bureau ouvert",
    description:
      "Nomades et entrepreneurs en semaine — networking informel au bar après 16 h.",
    date: "2026-01-01",
    time: "9:00 AM",
    location: "Cabarete",
    venue: "Cowork Cabarete",
    venueSlug: "cowork-cabarete",
    category: "business",
    format: "physical",
    recurrence: "weekdays",
    imageEmoji: "💼",
  },
  {
    id: "batey-salsa-weekly",
    title: "Soirée salsa à El Batey",
    description:
      "Cours débutant puis danse sociale jusqu'à tard. Pas besoin de partenaire.",
    date: "2026-01-01",
    time: "8:00 PM",
    location: "Sosúa",
    venue: "El Batey",
    venueSlug: "el-batey-sosua",
    category: "dance",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 3,
    imageEmoji: "💃",
  },
  {
    id: "sosua-volleyball-weekly",
    title: "Volley-ball de plage à Sosúa",
    description:
      "Matchs informels chaque semaine sur le sable. Il suffit de se présenter.",
    date: "2026-01-01",
    time: "4:00 PM",
    location: "Sosúa",
    venue: "Playa Sosúa",
    category: "sports",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 4,
    imageEmoji: "🏐",
  },
  {
    id: "lax-reggae-friday",
    title: "Reggae night au LAX (vendredi)",
    description:
      "Reggae et roots chaque vendredi sur la baie — une fête hebdomadaire iconique.",
    date: "2026-01-01",
    time: "9:00 PM",
    location: "Cabarete",
    venue: "LAX Cabarete",
    venueSlug: "lax-cabarete",
    category: "parties",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 5,
    trending: true,
    imageEmoji: "🪩",
  },
  {
    id: "batey-open-mic-weekly",
    title: "Open mic à El Batey",
    description:
      "Chanteurs, poètes et humoristes. Scène underground, public bilingue.",
    date: "2026-01-01",
    time: "8:00 PM",
    location: "Sosúa",
    venue: "El Batey",
    venueSlug: "el-batey-sosua",
    category: "performances",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 2,
    imageEmoji: "🎤",
  },
  {
    id: "sea-horse-saturday-market",
    title: "Marché du samedi à Sea Horse Ranch",
    description:
      "Achetez local chaque samedi avec artisans locaux, nourriture fraîche, produits bio et mode boutique sur la pelouse du Tennis Club de Sea Horse Ranch.",
    date: "2026-01-01",
    time: "10:00 AM - 1:00 PM",
    location: "Cabarete-Sosúa",
    venue: "Sea Horse Ranch Tennis Club Lawn",
    venueSlug: "sea-horse-ranch",
    category: "food-drinks",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6,
    sourceUrl: "https://www.sea-horse-ranch.com",
    imageEmoji: "🧺",
  },
  {
    id: "ocean-world-daily",
    title: "Ocean World Adventure Park",
    description:
      "Parc marin ouvert tous les jours à Cofresí — dauphins, otaries et requins, oiseaux exotiques, snorkeling sur récif et toboggan géant. Prévoyez 4 à 6 heures.",
    date: "2026-01-01",
    time: "9:00 AM - 6:00 PM",
    location: "Puerto Plata",
    address: "Cofresí, Puerto Plata",
    venue: "Ocean World Adventure Park",
    venueSlug: "ocean-world",
    category: "festivals",
    format: "physical",
    recurrence: "daily",
    sourceUrl:
      "https://es.godominicanrepublic.com/que-hacer/ocean-world-adventure-park",
    imageEmoji: "🐬",
  },
  {
    id: "charcos-damajagua-daily",
    title: "27 Charcos de Damajagua — Horaires",
    description:
      "Randonnées guidées entre cascades et bassins de calcaire — la plupart des tours couvrent sept chutes ; les 27 pour les plus sportifs. ~1 h de Puerto Plata.",
    date: "2026-01-01",
    time: "8:30 AM - 4:00 PM",
    location: "Puerto Plata",
    venue: "27 Charcos de Damajagua",
    venueSlug: "charcos-damajagua",
    category: "sports",
    format: "physical",
    recurrence: "daily",
    sourceUrl:
      "https://es.godominicanrepublic.com/que-hacer/27-charcos-de-damajagua",
    imageEmoji: "💧",
  },
  {
    id: "fortaleza-san-felipe-daily",
    title: "Fortaleza San Felipe — Horaires du musée",
    description:
      "Forteresse espagnole du XVIe siècle et musée — canons d'origine, armes coloniales et vue sur l'Atlantique. Coucher de soleil au parc La Puntilla.",
    date: "2026-01-01",
    time: "10:00 AM - 6:00 PM",
    location: "Puerto Plata",
    address: "Av. Gral. Gregorio Luperón",
    venue: "Fortaleza San Felipe",
    venueSlug: "fortaleza-san-felipe",
    category: "festivals",
    format: "physical",
    recurrence: "daily",
    sourceUrl:
      "https://es.godominicanrepublic.com/que-hacer/fortaleza-san-felipe",
    imageEmoji: "🏰",
  },
  {
    id: "museo-ambar-weekdays",
    title: "Museo del Ámbar — Horaires en semaine",
    description:
      "Manoir victorien au centre historique — fossiles d'ambre dominicain avec lézards, scorpions et insectes vieux de millions d'années.",
    date: "2026-01-01",
    time: "9:00 AM - 5:00 PM",
    location: "Puerto Plata",
    address: "Calle Duarte 61",
    venue: "Museo del Ámbar",
    venueSlug: "museo-ambar",
    category: "festivals",
    format: "physical",
    recurrence: "weekdays",
    sourceUrl: "https://es.godominicanrepublic.com/que-hacer/museo-del-ambar",
    imageEmoji: "🟠",
  },
  {
    id: "museo-ambar-saturday",
    title: "Museo del Ámbar — Horaires du samedi",
    description:
      "Horaires réduits le samedi au musée de l'ambre du centre de Puerto Plata. Fermé le dimanche.",
    date: "2026-01-01",
    time: "9:00 AM - 3:00 PM",
    location: "Puerto Plata",
    address: "Calle Duarte 61",
    venue: "Museo del Ámbar",
    venueSlug: "museo-ambar",
    category: "festivals",
    format: "physical",
    recurrence: "weekly",
    recurrenceDay: 6,
    sourceUrl: "https://es.godominicanrepublic.com/que-hacer/museo-del-ambar",
    imageEmoji: "🟠",
  },
  {
    id: "teleferico-puerto-plata-daily",
    title: "Téléphérique de Puerto Plata",
    description:
      "Téléphérique vers le pic Isabel de Torres — statue du Christ et jardins botaniques. Vérifiez s'il est en service ; des travaux ont parfois fermé la cabine — tours en camion safari possibles.",
    date: "2026-01-01",
    time: "8:30 AM - 5:00 PM",
    location: "Puerto Plata",
    address: "C. del Teleférico",
    venue: "Teleférico Puerto Plata",
    venueSlug: "teleferico-puerto-plata",
    category: "sports",
    format: "physical",
    recurrence: "daily",
    sourceUrl: "https://es.godominicanrepublic.com/destinos/puerto-plata",
    imageEmoji: "🚡",
  },
  {
    id: "cayo-arena-tours-daily",
    title: "Cayo Arena — Excursions en bateau",
    description:
      "Banc de sable (Cayo Paraíso) en bateau depuis Punta Rucia — ~25 minutes par trajet. Eau turquoise peu profonde, sable blanc et snorkeling. Départs le matin chez la plupart des opérateurs.",
    date: "2026-01-01",
    time: "8:00 AM - 12:00 PM",
    location: "Puerto Plata",
    venue: "Cayo Arena",
    venueSlug: "cayo-arena",
    category: "sports",
    format: "physical",
    recurrence: "daily",
    sourceUrl: "https://es.godominicanrepublic.com/que-hacer/cayo-arena",
    imageEmoji: "🏝️",
  },
];

export function getRecurringEvents(locale: Locale = "en"): Event[] {
  if (locale === "es") return RECURRING_ES;
  if (locale === "fr") return RECURRING_FR;
  return RECURRING_EN;
}
