/**
 * EN ↔ ES ↔ FR equivalents for North Coast event search.
 * Matching expands both query and document tokens through this lexicon so
 * English searches find Spanish/French titles (and the reverse) without
 * per-event aliases.
 */

export const SEARCH_SYNONYM_GROUPS: readonly (readonly string[])[] = [
  // Seasons
  ["spring", "primavera", "printemps"],
  ["summer", "verano", "été", "ete"],
  ["autumn", "fall", "otoño", "otono", "automne"],
  ["winter", "invierno", "hiver"],

  // Months
  ["january", "enero", "janvier"],
  ["february", "febrero", "février", "fevrier"],
  ["march", "marzo", "mars"],
  ["april", "abril", "avril"],
  ["may", "mayo", "mai"],
  ["june", "junio", "juin"],
  ["july", "julio", "juillet"],
  ["august", "agosto", "août", "aout"],
  ["september", "septiembre", "septembre"],
  ["october", "octubre", "octobre"],
  ["november", "noviembre", "novembre"],
  ["december", "diciembre", "décembre", "decembre"],

  // Days
  ["monday", "lunes", "lundi"],
  ["tuesday", "martes", "mardi"],
  ["wednesday", "miércoles", "miercoles", "mercredi"],
  ["thursday", "jueves", "jeudi"],
  ["friday", "viernes", "vendredi"],
  ["saturday", "sábado", "sabado", "samedi"],
  ["sunday", "domingo", "dimanche"],
  ["weekend", "fin de semana", "fin-de-semana", "week-end"],

  // Markets / fairs / bazaars
  ["bazaar", "bazar", "bazars", "bazaars"],
  ["market", "markets", "mercado", "mercados", "marché", "marche"],
  ["flea", "pulgas", "brocante"],
  ["artisan", "artesano", "artesanal", "artisanat"],
  ["craft", "crafts", "artesanía", "artesania"],
  ["vendor", "vendors", "vendedor", "vendedores", "vendeur"],
  ["booth", "stand", "carpa", "puesto"],

  // Event shapes (feria bridges fair ↔ festival in DR usage)
  ["concert", "concierto", "concerts", "conciertos"],
  ["music", "musica", "musique"],
  ["party", "parties", "fiesta", "fiestas", "soirée", "soiree", "fête", "fete"],
  ["festival", "festivals", "feria", "ferias", "fair", "fairs", "foire"],
  ["carnival", "carnaval"],
  ["dance", "dancing", "baile", "bailar"],
  ["night", "nights", "noche", "noches", "soir", "nuit"],
  ["day", "days", "día", "dia", "días", "dias", "journée", "journee"],
  ["live", "vivo"],
  ["workshop", "taller", "ateliers", "atelier"],
  ["class", "classes", "clase", "clases", "cours"],
  ["lesson", "lessons", "lección", "leccion", "leçon", "lecon"],
  ["tournament", "torneo", "tournoi"],
  ["championship", "campeonato", "championnat"],
  ["game", "games", "partido", "partidos", "match", "matches"],
  ["race", "carreras", "carrera", "course"],
  ["parade", "desfile", "défilé", "defile"],
  ["exhibition", "exposición", "exposicion", "exposition", "muestra"],
  ["gallery", "galería", "galeria", "galerie"],
  ["cinema", "cine", "movie", "movies", "película", "pelicula", "film"],
  ["theater", "theatre", "teatro"],
  ["comedy", "comedia", "humour", "humor"],
  ["show", "shows", "espectáculo", "espectaculo", "spectacle"],
  ["brunch"],
  ["dinner", "cena", "dîner", "diner"],
  ["lunch", "almuerzo", "déjeuner", "dejeuner"],
  ["breakfast", "desayuno"],
  ["sunset", "atardecer"],
  ["sunrise", "amanecer"],
  ["beach", "playa", "plage"],
  ["pool", "piscina", "piscine"],
  ["yacht", "yachts", "yate", "yates"],
  ["boat", "barco", "bateau"],
  ["cruise", "crucero", "croisière", "croisiere"],
  ["tour", "tours"],
  ["adventure", "aventura"],
  ["excursion", "excursión", "excursions"],
  ["culture", "cultura", "cultural"],
  ["nightlife", "nocturna"],
  ["wellness", "bienestar"],
  ["meditation", "meditación", "meditacion", "méditation"],
  ["fitness", "entrenamiento"],
  ["family", "familia", "famille", "familiar"],
  ["kids", "niños", "ninos", "enfants", "children", "child"],
  ["free", "gratis", "gratuit"],
  ["ticket", "tickets", "entrada", "entradas", "billet", "billets"],
  ["christmas", "navidad", "noël", "noel"],
  ["easter", "pascua", "pâques", "paques"],

  // Sports
  ["baseball", "béisbol", "beisbol"],
  ["softball", "softbol"],
  ["soccer", "football", "fútbol", "futbol"],
  ["volleyball", "voleibol"],
  ["basketball", "baloncesto"],
  ["tennis", "tenis"],
  ["triathlon", "triatlón", "triatlon"],
  ["marathon", "maratón", "maraton"],
  ["kitesurf", "kitesurfing", "kiteboarding", "kiteboard"],
  ["windsurf", "windsurfing"],
  ["surf", "surfing", "surfear"],
  ["boxing", "boxeo", "boxe"],

  // Places / room types often searched in English against Spanish copy
  ["terrace", "terraza", "terrasse"],
  ["rooftop", "azotea"],
  ["restaurant", "restaurante"],
  ["club", "clubs", "discoteca", "discothèque", "discotheque"],
  ["hotel", "hotels", "hôtel"],
  ["park", "parque", "parc"],
  ["church", "iglesia", "église", "eglise"],
  ["museum", "museo", "musée", "musee"],
];

/** Function words ignored in multi-token AND queries. */
export const SEARCH_STOPWORDS: ReadonlySet<string> = new Set(
  [
    "a",
    "an",
    "the",
    "of",
    "and",
    "or",
    "at",
    "in",
    "on",
    "to",
    "for",
    "with",
    "de",
    "del",
    "la",
    "las",
    "el",
    "los",
    "y",
    "e",
    "en",
    "un",
    "una",
    "unos",
    "unas",
    "al",
    "por",
    "para",
    "con",
    "le",
    "les",
    "des",
    "du",
    "et",
    "ou",
    "au",
    "aux",
    "sur",
    "dans",
  ].map((w) => w.normalize("NFD").replace(/\p{M}/gu, "")),
);
