/** Street lines harvested from seed event addresses (slug → street, no city). */
export const VENUE_STREET_ADDRESS: Readonly<Record<string, string>> = {
  "ambar-lounge-pop": "Av. Luis Ginebra 45-a",
  "amber-cove": "KM 10 Carretera Puerto Plata–Navarrete, Bahía de Maimón",
  "anfiteatro-la-puntilla": "La Puntilla",
  "aura-beach-club-cabarete": "Calle Principal",
  "blue-ice-pianobar-sosua": "Calle Dr. Rosen, El Batey",
  "blue-jacktar-playa-dorada": "Centro de Convenciones, Playa Dorada",
  "brugal-rum-center": "Carretera Maimón",
  "calle-sombrillas": "Calle San Felipe, between Calle Beller & Calle Duarte",
  "camara-comercio-puerto-plata": "Calle Beller No. 17, Salón de Eventos Fernando Cueto",
  "casa-caribe-puerto-plata": "Av. Luis Ginebra #52",
  "casa-coco-sosua": "Pedro Clisante 3",
  "casa-de-la-cultura": "Facing Parque Central, Calle Separación",
  "castaways-sosua": "Casa Linda Villas Phase 7-9, Carretera El Choco",
  "charco-los-militares": "MCF3+P2, Tubagua",
  "cheers-bar-sosua": "Calle Pedro Clisante",
  "cigar-town-pop": "Avenida Luis Ginebra No. 56",
  "the-hideout-puerto-plata": "Av. Luis Ginebra #56, Segundo Nivel",
  "classic-cars-dominicana": "Victrola 037 Arte Café",
  "club-deportivo-fantastico": "Calle 1ra",
  "coconut-cove": "Bajo Hondo, Coconut Cove",
  "coconuts-playa-encuentro": "Playa Encuentro",
  "cofresi-palm-beach-spa": "1 Paradise Drive, Playa Cofresí",
  "crazy-lobster-maimon": "Caseta 21, Playa Los Cocos, Maimón",
  "cremo-cigar-bar": "C. José del Carmen Ariza 47",
  "cuartel-bomberos-puerto-plata": "Av. Gral. Gregorio Luperón (Malecón) & Av. Sánchez",
  "d-classico-sosua": "Calle Pedro Clisante, El Batey",
  "del-oro-chocolate-factory": "C. Principal, Barrio Las Yaguitas",
  "desarrollo-fitness-cabarete": "Cabarete, Puerto Plata",
  "disco-club-brugal": "Depósitos de Brugal, Calle Duarte",
  "don-limon-cofresi": "5, Cofresí",
  "drifter-cabarete": "Cabarete Bay Beach 5",
  "el-batey-sosua": "Parque Las Flores, El Batey",
  "el-carey-puerto-plata": "Calle Reina Isabel",
  "el-cocotazo-cafe": "Agualina Kitebeach Hotel, Carretera Principal, Kite Beach",
  "el-colibri-hotel": "141 Pedro Clisante",
  "el-mirador-de-finely": "Calle Esmeralda 53, Urbanización Cerro Mar",
  "estadio-leonel-placido": "Calle Hugo Kunhardt",
  "faro-puerto-plata": "Parque La Puntilla, west end of the Malecón",
  "finca-papirucho": "HFW7+4FJ, Yásica Arriba",
  "finish-line-sosua": "Calle Ayuntamiento 1",
  "flip-flop-sports-bar-sosua": "2 Calle Duarte",
  "fortaleza-san-felipe": "Av. Gral. Gregorio Luperón",
  "fun-city": "Carretera Puerto Plata–Sosúa km 8½, Highway 5",
  "gran-ventana-beach-resort": "Complejo Hotelero Playa Dorada s/n, Puerto Plata",
  "grand-prix-puerto-plata": "Av. Manolo Tavares Justo esq. Presidente Caamaño #1, Edificio Grand Prix (Bomba Next), La Javilla",
  "grecialandia": "Carretera Principal, Residencia Grecia, Sabana del Corozo, El Cupey",
  "gregorio-luperon-airport": "Carretera Puerto Plata–Sosúa, Aeropuerto Internacional Gregorio Luperón (POP)",
  "gregorio-luperon-museum": "Calle 12 de Julio #54",
  "ground-zero-disco": "Km 18, Carretera Puerto Plata–Sosúa, frente al Aeropuerto Gregorio Luperón",
  "gym-sov-sosua-ocean-village": "Carretera Sosúa–Cabarete Km 2",
  "gypsy-bowls-cabarete": "Carretera Principal",
  "hacienda-cufa": "La Mariposa",
  "handmade-the-brand": "Calle Duarte 37",
  "hard-rock-sosua": "Calle Duarte 7",
  "hms-valeria": "Dr. Rosen 28",
  "hotel-ocean-winds": "Calle Guayacanes 79",
  "hotel-villa-taina": "Calle Principal 1",
  "hotel-voramar-sosua": "Calle Alejo Martínez, Playa Chiquita",
  "iberostar-waves-costa-dorada": "Carretera Luperón Km 4, Costa Dorada",
  "international-school-sosua": "La Mulata #1, El Batey",
  "ivan-garcia-teatro-escuela": "Calle Profesor Juan Bosch #72",
  "jamao-al-norte": "Parque Central, Jamao al Norte, Espaillat",
  "kite-beach": "Kite Beach",
  "kite-street-pop": "Calle Sánchez, Centro",
  "la-casita-de-papi": "Carretera Principal, Central Beach",
  "la-chabola-cabarete": "Callejón de la Loma",
  "la-confluencia-museum": "Calle 12 de Julio #39",
  "la-lola-malecon": "Avenida Gregorio Luperón, Malecón",
  "la-rejoya": "M9J3+5V3, Juan de Nina / Camú",
  "laguna-sov": "Carretera Sosúa–Cabarete km 2",
  "latinwok-plaza-uno": "Plaza 1, Av. Luis Ginebra",
  "le-petit-francois": "Playa Dorada G1, El Pueblito / Playa Chaparral, Puerto Plata",
  "letrero-puerto-plata": "Av. Gregorio Luperón (Malecón), road bend below Anfiteatro La Puntilla",
  "liquid-blue-cabarete": "Calle Principal #87",
  "lokuras-pop": "Calle Profesor Juan Bosch #11, near Junta Central Electoral",
  "long-beach-puerto-plata": "Av. Gregorio Luperón (Malecón), Long Beach",
  "los-tres-cocos-cofresi": "R74F+R59 La Roka, Cofresí",
  "love-does-sosua": "Pedro Clisante 10, frente al supermercado Playero",
  "luna-lounge-lcb": "Av. Luis Ginebra #42, behind Plaza Amapola",
  "macorix-house-of-rum": "Av. Francisco Alberto Caamaño",
  "meclao-rooftop": "Av. Luis Ginebra",
  "museo-ambar": "Calle Duarte 61",
  "natura-cabana": "Paseo del Sol 5",
  "nonas-grill-kitchen": "Calle María Montes 16, behind Super Pola, El Batey",
  "nova-salud-bienestar": "Calle Margarita Mears #6",
  "ocean-one-cabarete": "Calle Principal",
  "ocean-world": "Cofresí",
  "outback-adventures": "Plaza Turisol, Av. Gregorio Luperón",
  "paella-pop-el-pueblito": "Playa El Pueblito",
  "parada-tipica-el-choco": "Carretera principal Sosúa–Cabarete (vis-à-vis Ocean Village / Plaza Buen Gusto)",
  "parque-jose-briceno": "Av. Hermanas Mirabal",
  "parque-las-flores-sosua": "Parque Las Flores, El Batey",
  "parque-nacional-el-choco": "Callejón de la Loma",
  "paseo-dona-blanca": "Between Calle Beller & Calle John F. Kennedy",
  "pingui-bar": "C. B",
  "playa-cofresi": "Cofresí Beach",
  "playa-costambar": "Costambar beach, to the left of El Carey Restaurant, Calle Reina Isabel",
  "playa-dorada-golf": "Playa Dorada, Puerto Plata",
  "playa-encuentro": "Playa Encuentro",
  "playa-los-charamicos": "Playa Los Charamicos",
  "plaza-independencia": "Calle San Felipe",
  "plaza-juan-brugal": "Calle Carretera Luperón, frente a Depósitos Ferreteros",
  "plaza-sanchez-imbert": "Calle Sánchez, Imbert",
  "pop-cinemas-playa-dorada": "Calle Principal Playa Dorada 538",
  "project-paradise-cabarete": "Costa Azul J6",
  "rancho-catalina-puerto-plata": "El Cupey",
  "restaurant-maria-sov": "Carretera Sosúa–Cabarete km 2, Ocean Village Deluxe",
  "rincon-caliente-guananico": "Rincón Caliente, Guananico",
  "rio-martinico": "Madre Vieja",
  "rum-legacy-museum": "Calle Beller #11A",
  "santa-fe-sov": "Ocean Village Deluxe, Sosúa Ocean Village",
  "senor-rock-playa-dorada": "Playa Dorada Plaza, C. Principal",
  "smileys-bar-sosua": "Calle Pedro Clisante",
  "sosua-diving-center": "La Puntilla 24",
  "sosua-food-market": "Calle Anacaona & Calle Pablo Neruda",
  "sosua-jewish-museum": "Calle Alejo Martínez & Calle Rosen",
  "spotland-puerto-plata": "Av. Luis Ginebra",
  "sunset-grill-velero": "Calle La Punta 1, Velero Beach Resort",
  "tabacalera-cremo": "Calle San Felipe 8",
  "taino-bay": "Av. Antigua Vía Férrea, Muelle Turístico",
  "tasty-food-park-puerto-plata": "Av. 27 de Febrero",
  "teleferico-puerto-plata": "C. del Teleférico",
  "templo-de-las-americas": "La Isabela / El Castillo, Luperón, Puerto Plata",
  "terramar-pickleball-club": "Cabarete / Sosúa, Puerto Plata",
  "trolley-city-tours": "Sosúa route — key points & renovation works",
  "twenty-disco-lounge": "Playa Dorada Mall, Puerto Plata",
  "victrola-037": "Av. Gral. Gregorio Luperón esq. Padre Castellanos",
  "vinoteca-wine-house": "Carretera Luperón Km 4.5, Hotel Marien, Costa Dorada",
  "vip-beach-lifestyles-resort": "Cofresí Beach #1",
  "vivonte-cigar-factory": "C. Separación & Calle Prof. Juan Bosch",
  "waterfront-playa-alicia": "Playa Alicia, El Batey",
  "zona-acapella-club": "Cuarto de Milla, Av. Gral. Gregorio Luperón",
};

export function getVenueStreetAddress(slug?: string | null): string | undefined {
  if (!slug?.trim()) return undefined;
  const street = VENUE_STREET_ADDRESS[slug.trim()];
  return street?.trim() || undefined;
}
